import {filterResources, validateManifest, stageUpdate} from './core.js';
const $ = selector => document.querySelector(selector);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = s => s ? new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(s)) : 'Niet vastgelegd';
const layers = {national:'Landelijke richtlijn',local:'Lokale afspraak',regional:'Regionaal / transmuraal',patient:'Patiënteninformatie',social:'Sociaal domein'};
const topics = {neus:'Neusklachten',duizeligheid:'Duizeligheid',gehoor:'Gehoorverlies',oncologie:'Oncologie'};
const tasks = {history:'Anamnese',diagnostics:'Diagnostiek',referral:'Verwijzen & samenwerken',shared_decision:'Informeren & samen beslissen',followup:'Opvolgen',urgency:'Urgentie',examination:'Lichamelijk onderzoek',treatment:'Behandeling'};
const filters = {topic:'neus',task:'',layer:'',demo:false};
let sources=[], actions=[], modules=[], resources=[], selected=new Set(), update='idle', toastTimer;
const read = async path => { const response=await fetch(path); if(!response.ok) throw new Error('Gegevens niet bereikbaar'); return response.json(); };
function toast(message){ $('#toast').textContent=message; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800); }
const external = (url,label,cls='') => '<a class="'+cls+'" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+' ↗</a>';
function makeResources(){
 const real=actions.map(a=>({id:a.id,title:a.title,description:a.record_type==='navigation_only'?'Verwijzing naar de bron over positionele downbeatnystagmus. Geen zelfstandige diagnostische regel.':'Bronpassage over '+(a.id==='allergy-child-history'?'anamnese bij kinderen binnen de allergiemodule.':'anamnese binnen de module luchtwegallergie.'),topics:[a.source_id==='bppd-anterior'?'duizeligheid':'neus'],tasks:[a.action],layer:'national',demo:false,source:sources.find(s=>s.id===a.source_id),record:a,owner:'Richtlijnendatabase · initiatief NVKNO',version:'Overdracht 04-10-2026'}));
 const examples=[
  ['demo-local','Werkafspraak polikliniek KNO','Plaats voor een lokale procesafspraak met eigenaar, bereik en revisiedatum. Er is nog geen echte afspraak aangeleverd.','local',['history','referral']],
  ['demo-region','Samenwerkingsafspraak in de regio','Laat een regionale of transmurale bron naast de landelijke richtlijn zien. Deze voorbeeldkaart bevat geen verwijscriteria.','regional',['referral','followup']],
  ['demo-patient','Informatie om samen te bespreken','Plaats voor een specifiek gecontroleerde patiëntenbron. Er is nog geen gekoppelde patiëntenfolder beschikbaar.','patient',['shared_decision']],
  ['demo-social','Ondersteuning in het sociaal domein','Plaats voor een geverifieerde gemeentelijke of welzijnsbron. Contacten, bereik en toegangsvoorwaarden moeten nog worden aangeleverd.','social',['referral','followup']]
 ].map(([id,title,description,layer,t])=>({id,title,description,topics:['neus','duizeligheid','gehoor'],tasks:t,layer,demo:true,owner:'Demonstratie · geen echte organisatie',version:'Modelvoorbeeld v0.1'}));
 return [...real,...examples];
}
function heading(kicker,title,description,extra=''){return '<div class="heading"><div><div class="eyebrow">'+kicker+'</div><h1>'+title+'</h1><p class="intro">'+description+'</p></div>'+extra+'</div>';}
function card(r,board=false){return '<article class="card '+(r.layer==='social'?'social':r.layer==='patient'?'patient':r.layer!=='national'?'local':'')+'"><div><span class="badge '+(r.demo?'demo':'')+'">'+esc(layers[r.layer])+'</span></div><h3>'+esc(r.title)+'</h3><div class="meta">'+esc(r.owner)+'</div><p>'+esc(r.description)+'</p><div class="card-bottom"><div class="tags">'+r.tasks.map(t=>'<span>'+tasks[t]+'</span>').join('')+'</div><span class="badge '+(r.demo?'demo':'warning')+'">'+(r.demo?'Demonstratie · geen broninhoud':'Redactioneel te beoordelen')+'</span><div class="actions"><button data-open="'+r.id+'">Bekijk bronkaart</button><button data-pin="'+r.id+'" class="'+(selected.has(r.id)?'saved':'')+'">'+(selected.has(r.id)?'✓ Op Chipboard':'+ Chipboard')+'</button></div><div class="match">'+(board?'Afzonderlijke bron · '+esc(r.version):'Gevonden via onderwerp / taak. Geen beoordeling van patiëntgeschiktheid.')+'</div></div></article>';}
function options(dict,current,all){return '<option value="">'+all+'</option>'+Object.entries(dict).map(([v,label])=>'<option value="'+v+'" '+(current===v?'selected':'')+'>'+label+'</option>').join('');}
function library(){
 const found=filterResources(resources,filters);
 return heading('BRONNENWERKPLEK','De juiste bron, binnen handbereik.','Vind richtlijnpassages en leg afspraken en informatie ernaast. Elke bron houdt zijn eigen context.', '<span class="badge warning">Prototype · beperkte voorbeeldset</span>')+
 '<div class="searchbox"><div class="search-title">Waar werk je aan?</div><div class="filters"><label>Onderwerp<select id="topic">'+options(topics,filters.topic,'Alle onderwerpen')+'</select></label><label>Taak<select id="task">'+options(tasks,filters.task,'Alle taken')+'</select></label><label>Type bron<select id="layer">'+options(layers,filters.layer,'Alle typen')+'</select></label><button id="reset">Wis filters</button></div><div class="filter-foot"><span>Vaste bibliotheekfilters · geen patiëntkenmerken invullen</span><label class="toggle"><input type="checkbox" id="demo" '+(filters.demo?'checked':'')+'>Toon demonstratie van andere bronlagen</label></div></div>'+
 '<div class="stats"><span><strong>'+new Set(actions.map(a=>a.source_id)).size+'</strong>richtlijnmodules</span><span><strong>'+actions.length+'</strong>voorbeeldrecords</span><span><strong>0</strong>professioneel goedgekeurd</span><span><strong>0</strong>echte lokale afspraken</span></div>'+
 (filters.demo?'<div class="notice">De paarse demonstratiekaarten laten zien hoe bronnen gecombineerd kunnen worden. Ze bevatten geen echte afspraken, patiëntinformatie of sociale verwijzingen.</div>':'')+
 '<div class="section-row"><h2>Bronnen voor jouw werk</h2><span class="count" role="status">'+found.length+' kaarten · '+found.filter(r=>!r.demo).length+' uit het overdrachtspakket</span></div><div class="grid">'+(found.length?found.map(r=>card(r)).join(''):'<div class="empty"><h3>Voor deze selectie is nog geen inhoud beschikbaar.</h3><p>De voorbeeldset bevat alleen neusklachten en positieduizeligheid. Er worden geen antwoorden gegenereerd.</p>'+external('https://richtlijnendatabase.nl/','Zoek in de officiële Richtlijnendatabase')+'</div>')+'</div>';
}
function board(){
 const rows=resources.filter(r=>selected.has(r.id));
 return heading('MIJN CHIPBOARD','Verschillende bronnen. Eén werkplek.','Zet bronnen naast elkaar voor je eigen overzicht. Er wordt geen gezamenlijk medisch advies van gemaakt.','<button id="clear-board">Maak bord leeg</button>')+
 '<div class="notice">Dit bord bestaat alleen zolang deze pagina openstaat. Het bevat bronverwijzingen; geen dossiers, notities of patiëntgegevens.</div>'+
 '<div class="section-row"><h2>Naast elkaar</h2><span class="count">'+rows.length+' geselecteerde bronnen</span></div><div class="board-grid">'+(rows.length?rows.map(r=>card(r,true)).join(''):'<div class="empty"><h3>Maak je eerste bronnenoverzicht</h3><p>Kies in de bronnenwerkplek “+ Chipboard”. Zet eventueel de demonstratie van andere bronlagen aan.</p><a href="#bibliotheek">Naar de bronnenwerkplek</a></div>')+'</div>'+
 (rows.length>1?'<div class="panel"><h2>Verschillen zichtbaar houden</h2><p>Een lokale afspraak vervangt niet automatisch een landelijke bron. Bij tegenstrijdigheid blijven beide zichtbaar en is beoordeling door de inhoudelijk verantwoordelijke nodig.</p><div class="table-wrap"><table><thead><tr><th>Bron</th><th>Bereik</th><th>Beoordeling</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.title)+'</td><td>'+esc(layers[r.layer])+'</td><td>'+(r.demo?'Geen echte inhoud':'Nog niet professioneel beoordeeld')+'</td></tr>').join('')+'</tbody></table></div></div>':'');
}
function modulePage(){return heading('MODULAIRE WERKPLEK','Aansluiten zonder alles te verbouwen.','Bronnen en applicaties krijgen een eigen modulekaart. Een vaste link opent de externe toepassing zonder patiënt- of zoekgegevens.')+
 '<div class="grid">'+modules.map(m=>'<article class="card"><span class="badge teal">'+(m.kind==='source-library'?'Actieve bronlaag':'Externe link')+'</span><h3>'+esc(m.name)+'</h3><p>'+(m.kind==='source-library'?'De eerste bronnenmodule in dit Chipboard. Gegevens staan los van de schermen en kunnen via een gecontroleerde release worden bijgewerkt.':'Opent het bestaande oncologieprototype. Geen gegevensuitwisseling of accountkoppeling geïmplementeerd.')+'</p><div class="card-bottom">'+external(m.url,'Open toepassing')+'<div class="actions"><button data-manifest="'+m.id+'">Bekijk modulecontract</button></div></div></article>').join('')+
 '<article class="card local"><span class="badge">Aansluitbaar model</span><h3>Andere Inforium- en CHIP-modules</h3><p>Notes, regionale afspraken, patiëntenbibliotheken en externe toepassingen kunnen aansluiten via hetzelfde bron- en modulecontract. Deze koppelingen zijn nog niet gerealiseerd.</p><button id="contract">Bekijk aansluitroute</button></article></div>'+
 '<div class="panel"><h2>Van bron naar werkvloer</h2><div class="steps"><div class="step"><strong>01 · Bronadapter</strong>Leest toegestane bronmetadata</div><div class="step"><strong>02 · Bronregister</strong>Versie, eigenaar en herkomst</div><div class="step"><strong>03 · Redactie</strong>Controle op inhoud en bereik</div><div class="step"><strong>04 · Chipboard</strong>Vinden, combineren en openen</div></div><p>Deze versie gebruikt lokale JSON-bestanden. Een centrale catalogus-API, authenticatie voor redacteuren en automatische bronadapters zijn vervolgbouw.</p></div>';}
function management(){
 const statuses=['idle','detected','staged','reviewed','released'], pos=statuses.indexOf(update);
 return heading('BRONNEN & UPDATES','Actueel houden, met controle ertussen.','Publicatie, geldigheidsbeoordeling en raadpleging zijn afzonderlijke datums. Een nieuwe datum is geen nieuwe medische goedkeuring.')+
 '<div class="panel"><div class="section-row"><h2>Probeer een bronwijziging</h2><span class="badge demo">Simulatie · alleen in dit scherm</span></div><p>Doorloop de beheerroute met fictieve metadata. De echte bronrecords worden niet gewijzigd.</p><div class="steps">'+['Wijziging gevonden','Conceptversie','Redactie gecontroleerd','Versie vrijgegeven'].map((s,i)=>'<div class="step '+(pos>i?'done':'')+'"><strong>'+('0'+(i+1))+'</strong>'+s+'</div>').join('')+'</div><p id="update-status" role="status">'+[
  'Start een fictieve wijziging om de vervolgstappen te bekijken.',
  'Een fictieve nieuwe bronversie is gevonden. De huidige catalogus blijft beschikbaar.',
  'Conceptversie klaar. Vergelijking: versie 1 → versie 2; fictieve wijziging in contactgegevens. Inhoud, hergebruik en gekoppelde kaarten moeten worden gecontroleerd.',
  'Democontrole afgerond. In productie is een bevoegde redacteur met vastgelegde identiteit vereist.',
  'Demoversie vrijgegeven. In productie volgt een geteste release; eerdere versies blijven via Git beschikbaar.'
 ][pos]+'</p><div class="actions">'+(update==='idle'?'<button id="detect" class="primary">Simuleer bronwijziging</button>':update!=='released'?'<button id="advance" class="primary">'+({detected:'Maak democoncept',staged:'Simuleer redactionele controle',reviewed:'Geef demoversie vrij'}[update])+'</button>':'')+'<button id="reset-update">Herstart demonstratie</button></div></div>'+
 '<div class="panel"><h2>Bronregister</h2><p>'+sources.length+' bronverwijzingen in het pakket, waarvan '+new Set(actions.map(a=>a.source_id)).size+' inhoudelijke richtlijnmodules. Laatst opnieuw geraadpleegde modulemetadata: 4 oktober 2026.</p><div class="table-wrap"><table><thead><tr><th>Bron</th><th>Publicatie</th><th>Geldigheid beoordeeld</th><th>Raadpleging pakket</th></tr></thead><tbody>'+sources.map(s=>'<tr><td>'+external(s.url,s.title)+'<small>Geen professionele goedkeuring van afgeleide records</small></td><td>'+date(s.published_at)+'</td><td>'+date(s.validity_assessed_at)+'</td><td>'+date(s.checked_at)+'</td></tr>').join('')+'</tbody></table></div></div><div class="panel"><h2>Als een bron verandert of niet opent</h2><p>Behoud de laatst gecontroleerde versie en datum. Zet hercontrole uit bij de eigenaar. Een technische fout bewijst niet dat medische informatie vervallen is. Het meegeleverde controlescript maakt een bereikbaarheidsrapport en wijzigt geen inhoud of goedkeuringsstatus.</p></div>';
}
function scope(){return heading('GEBRUIK & AFBAKENING','Een bronnenwerkplek voor professionals.','Dit prototype onderzoekt het vinden en combineren van kennis. Het is niet gereed voor klinische inzet.')+
 '<div class="two-columns"><section class="panel"><h2>Wat deze versie doet</h2><ul class="scope-list"><li>Bibliotheekmetadata filteren op onderwerp, taak en brontype.</li><li>Herleidbare bronkaarten naast elkaar tonen.</li><li>Vaste externe links openen zonder contextoverdracht.</li><li>Een modulaire structuur en beheerroute demonstreren.</li></ul></section><section class="panel"><h2>Grenzen van deze versie</h2><ul class="scope-list"><li>Geen patiëntinvoer, dossiers, uploads of vrije notities.</li><li>Geen diagnose, triage, dosering of gepersonaliseerde aanbeveling.</li><li>Geen taalmodel of gegenereerde medische antwoorden.</li><li>Geen professionele validatie van de drie voorbeeldrecords.</li></ul></section></div>'+
 '<div class="panel"><h2>MDR: ontwerpkeuze, geen vrijstelling</h2><p>Het ontbreken van patiëntgegevens of generatieve AI garandeert niet dat software buiten de MDR valt. Beoogd gebruik, functies en hun samenhang zijn bepalend. Ook zoeken kan een medisch doel dienen. Nieuwe functies en modulecombinaties vragen daarom een kwalificatiebeoordeling vóór klinische inzet.</p>'+external('https://health.ec.europa.eu/document/download/b45335c5-1679-4c71-a91c-fc7a4d37f12b_en?filename=md_mdcg_2019_11_guidance_qualification_classification_software_en.pdf','MDCG 2019-11 rev.1 · juni 2025')+'</div><div class="panel"><h2>Gegevens & herkomst</h2><p>Filters en bordselecties blijven in paginageheugen. Er zijn geen analytics, cookies, externe lettertypen of AI-aanroepen toegevoegd. De hostingprovider ontvangt gewone webverzoeken; externe websites hanteren hun eigen privacybeleid.</p><p>Basis: Inforium_Richtlijnen_Codex_Overdracht.zip, versie 4 oktober 2026. De bronkaarten zijn beperkte redactionele voorbeelden. Geen volledige database, gecontroleerde patiëntenbibliotheek of regionale afsprakenbank.</p></div>';
}
function render(){
 const page=location.hash.slice(1)||'bibliotheek';
 const views={bibliotheek:library,board,modules:modulePage,beheer:management,kaders:scope};
 $('#main').innerHTML=(views[page]||library)();
 document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===page; a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 $('#board-count').textContent=selected.size;
}
function showDialog(html){$('#detail-body').innerHTML=html;$('#detail').showModal();}
function showResource(id){
 const r=resources.find(r=>r.id===id); if(!r)return;
 let html='<div class="dialog-top"><span class="badge '+(r.demo?'demo':'warning')+'">'+(r.demo?'Demonstratie':'Redactioneel te beoordelen')+'</span><button class="close" data-close>Sluiten ✕</button></div><h2 id="detail-title">'+esc(r.title)+'</h2><p>'+esc(r.description)+'</p>';
 if(r.demo) html+='<div class="notice">Geen echte afspraak of patiënteninformatie. Dit is een invulmodel voor een toekomstige bronkoppeling.</div><dl><dt>Type</dt><dd>'+esc(layers[r.layer])+'</dd><dt>Benodigde brongegevens</dt><dd>Eigenaar, regio, doelgroep, originele URL, versie, geldigheidsperiode, hergebruikrechten en redactionele controle.</dd><dt>Relatie tot landelijke bronnen</dt><dd>Aanvulling, afwijking of procesafspraak expliciet vastleggen; nooit stilzwijgend samenvoegen.</dd></dl>';
 else {
 const a=r.record,s=r.source;
 const labels={suspected_condition:'Toepassingsgebied: mogelijke luchtwegallergie',setting:'Setting: tweede / derde lijn',age_group:'Doelgroep: kinderen'};
 html+='<div class="notice">'+(a.record_type==='navigation_only'?'Uitsluitend bronnavigatie; geen zelfstandige diagnostische beslisregel.':'Deze kaart beschrijft een bronpassage, niet wat bij een individuele patiënt moet gebeuren.')+'</div><dl><dt>Inforium Notes · toepassingsgebied van de bron</dt><dd>'+(a.applicability.any_of.map(g=>g.all_of.map(c=>esc(labels[c.field]||c.field)).join(' én ')).filter(Boolean).join(' OF ') || 'Niet als zelfstandig criterium gemodelleerd')+'</dd><dt>Uitsluitingen</dt><dd>Niet volledig geïnventariseerd. Geen claim van volledige toepasbaarheid.</dd><dt>Bronsectie</dt><dd>'+esc(a.source_section)+'</dd><dt>Officiële aanbeveling</dt><dd>Lees in de oorspronkelijke module; niet volledig overgenomen.</dd><dt>Onderbouwing en overwegingen</dt><dd>Afzonderlijke secties in de bron. Lees samen met de aanbeveling.</dd><dt>Aanbevelingsmodaliteit in overdracht</dt><dd>'+esc({do:'Doen · beperkte redactionele interpretatie',not_applicable:'Niet van toepassing'}[a.modality]||a.modality)+'</dd><dt>Bewijszekerheid</dt><dd>Niet vastgelegd in het actierecord; geen GRADE-niveau toegekend.</dd><dt>Redactionele notitie</dt><dd>'+esc(a.review_note)+'</dd><dt>Publicatie / geldigheid beoordeeld</dt><dd>'+date(s.published_at)+' / '+date(s.validity_assessed_at)+'</dd><dt>Raadpleging in overdracht</dt><dd>'+date(s.checked_at)+'</dd></dl>'+external(s.url,'Open oorspronkelijke module','source-link')+'<p class="muted">Opent de bron niet? De status is dan onbekend; behoud de laatste controledatum en laat de bron opnieuw controleren.</p>';
 }
 showDialog(html);
}
document.addEventListener('click',event=>{
 const button=event.target.closest('button');if(!button)return;
 if(button.hasAttribute('data-close')) $('#detail').close();
 if(button.dataset.open)showResource(button.dataset.open);
 if(button.dataset.pin){const id=button.dataset.pin;selected.has(id)?selected.delete(id):selected.add(id);render();document.querySelector('[data-pin="'+id+'"]')?.focus();toast(selected.has(id)?'Bron toegevoegd aan je Chipboard':'Bron verwijderd van je Chipboard');}
 if(button.id==='reset'){Object.assign(filters,{topic:'',task:'',layer:'',demo:false});render();$('#topic').focus();}
 if(button.id==='clear-board'){selected.clear();render();$('#clear-board').focus();toast('Chipboard leeggemaakt');}
 if(['detect','advance','reset-update'].includes(button.id)){update=stageUpdate(update,button.id==='detect'?'detect':button.id==='advance'?'advance':'reset');render();($('#advance')||$('#reset-update')).focus();}
 if(button.dataset.manifest){const m=modules.find(m=>m.id===button.dataset.manifest);showDialog('<div class="dialog-top"><span class="badge">Modulecontract v1</span><button data-close>Sluiten ✕</button></div><h2 id="detail-title">'+esc(m.name)+'</h2><p>Dit manifest beschrijft alleen de module, de vaste bestemming en toegestane functies.</p><pre>'+esc(JSON.stringify(m,null,2))+'</pre>');}
 if(button.id==='contract')showDialog('<div class="dialog-top"><span class="badge">Aansluitroute</span><button data-close>Sluiten ✕</button></div><h2 id="detail-title">Een module toevoegen</h2><ol class="scope-list"><li>Leg eigenaar, bronrechten en beoogd gebruik vast.</li><li>Voeg een manifest toe aan data/modules.json met vaste HTTPS-link en patientData: false.</li><li>Map bronmetadata naar een eigen adapter; behoud versie en herkomst.</li><li>Laat inhoud en modulecombinatie beoordelen.</li><li>Valideer, test en publiceer een nieuwe versie via GitHub.</li></ol><p>Een link is nog geen API-integratie. Uitwisseling en authenticatie vereisen aanvullende bouw en toetsing.</p>');
});
document.addEventListener('change',e=>{
 if(['topic','task','layer'].includes(e.target.id)){const id=e.target.id;filters[id]=e.target.value;render();$('#'+id).focus();}
 if(e.target.id==='demo'){filters.demo=e.target.checked;render();$('#demo').focus();}
});
window.addEventListener('hashchange',()=>{render();$('#main').focus();});
try {
 [sources,actions,modules]=await Promise.all([read('./data/bronnen.json'),read('./data/voorbeeldacties.json'),read('./data/modules.json')]);
 modules.forEach(validateManifest); resources=makeResources();render();
} catch(error){$('#main').innerHTML='<div class="empty"><h1>De brongegevens konden niet worden geladen.</h1><p>Er worden geen vervangende antwoorden getoond. Probeer de pagina opnieuw te laden.</p><a href="./">Opnieuw laden</a></div>';console.error(error);}
