import {buildSearchIndex,searchResources} from './search.js';
import {decodeGroningen,filterGroningen,groningenKinds} from './groningen.js';
import {filterResources, validateManifest, stageUpdate} from './core.js';
const $ = selector => document.querySelector(selector);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = s => s ? new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(s)) : 'Niet vastgelegd';
const layers = {groningen:'Groningen · broninventaris',national:'Landelijke richtlijn',local:'Lokale afspraak',regional:'Regionaal / transmuraal',patient:'Patiënteninformatie',social:'Sociaal domein'};
const specialties = {kno:'KNO',cardiologie:'Cardiologie',oncologie:'Oncologie',radiotherapie:'Radiotherapie'};
const topics = {neus:'Neusklachten',duizeligheid:'Duizeligheid',gehoor:'Gehoorverlies','hoofd-hals':'Hoofd-halstumoren',atriumfibrilleren:'Atriumfibrilleren',hartrevalidatie:'Hartrevalidatie',borstkanker:'Borstkanker',longkanker:'Longcarcinoom'};
const tasks = {overview:'Richtlijnoverzicht',history:'Anamnese',diagnostics:'Diagnostiek',referral:'Verwijzen & samenwerken',shared_decision:'Informeren & samen beslissen',followup:'Opvolgen',urgency:'Urgentie',examination:'Lichamelijk onderzoek',treatment:'Behandeling'};
const filters = {specialty:'',topic:'',task:'',layer:'',demo:false};
let groningenPayload,groningenRecords=[],groningenPageIndex=0;
const groningenFilters={audience:'patient',kind:'',group:'',path:''};
let catalog=[], sources=[], actions=[], modules=[], resources=[], selected=new Set(), update='idle', toastTimer;
const read = async path => { const response=await fetch(path); if(!response.ok) throw new Error('Gegevens niet bereikbaar'); return response.json(); };
function toast(message){ $('#toast').textContent=message; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800); }
const external = (url,label,cls='') => '<a class="'+cls+'" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+' ↗</a>';
function makeResources(){
 const real=actions.map(a=>({id:a.id,title:a.title,description:a.record_type==='navigation_only'?'Verwijzing naar de bron over positionele downbeatnystagmus. Geen zelfstandige diagnostische regel.':'Bronpassage over '+(a.id==='allergy-child-history'?'anamnese bij kinderen binnen de allergiemodule.':'anamnese binnen de module luchtwegallergie.'),topics:[a.source_id==='bppd-anterior'?'duizeligheid':'neus'],tasks:[a.action],layer:'national',specialties:['kno'],demo:false,source:sources.find(s=>s.id===a.source_id),record:a,owner:'Richtlijnendatabase · initiatief NVKNO',version:'Overdracht 04-10-2026'}));
 const examples=[
  ['demo-local','Lokale werkafspraak','Plaats voor een lokale procesafspraak met eigenaar, bereik en revisiedatum. Er is nog geen echte afspraak aangeleverd.','local',['history','referral']],
  ['demo-region','Samenwerkingsafspraak in de regio','Laat een regionale of transmurale bron naast de landelijke richtlijn zien. Deze voorbeeldkaart bevat geen verwijscriteria.','regional',['referral','followup']],
  ['demo-patient','Informatie om samen te bespreken','Plaats voor een specifiek gecontroleerde patiëntenbron. Er is nog geen gekoppelde patiëntenfolder beschikbaar.','patient',['shared_decision']],
  ['demo-social','Ondersteuning in het sociaal domein','Plaats voor een geverifieerde gemeentelijke of welzijnsbron. Contacten, bereik en toegangsvoorwaarden moeten nog worden aangeleverd.','social',['referral','followup']]
 ].map(([id,title,description,layer,t])=>({id,title,description,specialties:Object.keys(specialties),topics:Object.keys(topics),tasks:t,layer,demo:true,owner:'Demonstratie · geen echte organisatie',version:'Modelvoorbeeld v0.1'}));
 const added=catalog.map(c=>({...c,source:c,description:(c.source_kind==='overview'?'Startpagina met toegang tot de oorspronkelijke richtlijnmodules.':'Verwijzing naar de oorspronkelijke richtlijnmodule.')+' Lees de inhoud en voorwaarden bij de bron.',layer:'national',demo:false,owner:'Richtlijnendatabase',navigation:true}));
 return [...real,...added,...examples];
}
function heading(kicker,title,description,extra=''){return '<div class="heading"><div><div class="eyebrow">'+kicker+'</div><h1>'+title+'</h1><p class="intro">'+description+'</p></div>'+extra+'</div>';}
function card(r,board=false,hit=null){return '<article class="card '+(r.layer==='social'?'social':r.layer==='patient'?'patient':r.layer!=='national'?'local':'')+'"><div><span class="badge '+(r.demo?'demo':'')+'">'+esc(layers[r.layer])+'</span></div><h3>'+esc(r.title)+'</h3><div class="meta">'+esc(r.owner)+'</div><p>'+esc(r.description)+'</p><div class="card-bottom"><div class="tags">'+[...(r.specialties||[]).map(k=>'<span>'+specialties[k]+'</span>')].join('')+r.tasks.map(t=>'<span>'+tasks[t]+'</span>').join('')+'</div><span class="badge '+(r.demo?'demo':'warning')+'">'+(r.demo?'Demonstratie · geen broninhoud':r.groningen?(r.locked?'Alleen metadata · mogelijk inloggen':'Inventaris 03-10-2026 · bronverwijzing'):r.navigation?(r.source_kind==='overview'?'Richtlijnoverzicht · bronverwijzing':'Richtlijnmodule · bronverwijzing'):'Redactioneel te beoordelen')+'</span><div class="actions"><button data-open="'+r.id+'">Bekijk bronkaart</button><button data-pin="'+r.id+'" class="'+(selected.has(r.id)?'saved':'')+'">'+(selected.has(r.id)?'✓ Op Chipboard':'+ Chipboard')+'</button></div>'+(hit?searchReason(hit):'')+'<div class="match">'+(board?'Afzonderlijke bron · '+esc(r.version):'Bronnavigatie · geen beoordeling van patiëntgeschiktheid.')+'</div></div></article>';}
function options(dict,current,all){return '<option value="">'+all+'</option>'+Object.entries(dict).map(([v,label])=>'<option value="'+v+'" '+(current===v?'selected':'')+'>'+label+'</option>').join('');}
function library(){
 const found=filterResources(resources.filter(r=>!r.groningen),filters);
 return heading('BRONNENWERKPLEK','De juiste bron, binnen handbereik.','Vind richtlijnpassages en leg afspraken en informatie ernaast. Elke bron houdt zijn eigen context.', '<span class="badge warning">Prototype · beperkte voorbeeldset</span>')+
 '<div class="searchbox"><div class="search-title">Waar werk je aan?</div><div class="filters"><label>Vakgebied<select id="specialty">'+options(specialties,filters.specialty,'Alle vakgebieden')+'</select></label><label>Onderwerp<select id="topic">'+options(Object.fromEntries(Object.entries(topics).filter(([id])=>!filters.specialty||resources.some(r=>!r.demo&&r.specialties.includes(filters.specialty)&&r.topics.includes(id)))),filters.topic,'Alle onderwerpen')+'</select></label><label>Taak<select id="task">'+options(tasks,filters.task,'Alle taken')+'</select></label><label>Type bron<select id="layer">'+options(Object.fromEntries(Object.entries(layers).filter(([id])=>id!=='groningen')),filters.layer,'Alle typen')+'</select></label><button id="reset">Wis filters</button></div><div class="filter-foot"><span>Vaste bibliotheekfilters · geen patiëntkenmerken invullen</span><label class="toggle"><input type="checkbox" id="demo" '+(filters.demo?'checked':'')+'>Toon demonstratie van andere bronlagen</label></div></div>'+
 '<div class="notice">Startselectie voor vier vakgebieden; geen volledige dekking. Overzichten openen de officiële richtlijn. Gedeelde bronnen worden één keer getoond.</div><div class="stats"><span><strong>'+(new Set(actions.map(a=>a.source_id)).size+catalog.filter(c=>c.source_kind==='module').length)+'</strong>geselecteerde modules</span><span><strong>'+catalog.filter(c=>c.source_kind==='overview').length+'</strong>richtlijnoverzichten</span><span><strong>0</strong>professioneel goedgekeurd</span><span><strong>0</strong>gevalideerde lokale afspraken</span></div>'+
 (filters.demo?'<div class="notice">De paarse demonstratiekaarten laten zien hoe bronnen gecombineerd kunnen worden. Ze bevatten geen echte afspraken, patiëntinformatie of sociale verwijzingen.</div>':'')+
 '<div class="section-row"><h2>Bronnen voor jouw werk</h2><span class="count" role="status">'+found.length+' kaarten · '+found.filter(r=>!r.demo).length+' bronkaarten</span></div><div class="grid">'+(found.length?found.map(r=>card(r)).join(''):'<div class="empty"><h3>Voor deze selectie is nog geen inhoud beschikbaar.</h3><p>De startselectie dekt niet alle onderwerpen en taken. Wis eventueel een filter. Er worden geen antwoorden gegenereerd.</p>'+external('https://richtlijnendatabase.nl/','Zoek in de officiële Richtlijnendatabase')+'</div>')+'</div>';
}
function board(){
 const rows=resources.filter(r=>selected.has(r.id));
 return heading('MIJN CHIPBOARD','Verschillende bronnen. Eén werkplek.','Zet bronnen naast elkaar voor je eigen overzicht. Er wordt geen gezamenlijk medisch advies van gemaakt.','<button id="clear-board">Maak bord leeg</button>')+
 '<div class="notice">Dit bord bestaat alleen zolang deze pagina openstaat. Het bevat bronverwijzingen; geen dossiers, notities of patiëntgegevens.</div>'+
 '<div class="section-row"><h2>Naast elkaar</h2><span class="count">'+rows.length+' geselecteerde bronnen</span></div><div class="board-grid">'+(rows.length?rows.map(r=>card(r,true)).join(''):'<div class="empty"><h3>Maak je eerste bronnenoverzicht</h3><p>Kies in de bronnenwerkplek “+ Chipboard”. Zet eventueel de demonstratie van andere bronlagen aan.</p><a href="#bibliotheek">Naar de bronnenwerkplek</a></div>')+'</div>'+
 (rows.length>1?'<div class="panel"><h2>Verschillen zichtbaar houden</h2><p>Een lokale afspraak vervangt niet automatisch een landelijke bron. Bij tegenstrijdigheid blijven beide zichtbaar en is beoordeling door de inhoudelijk verantwoordelijke nodig.</p><div class="table-wrap"><table><thead><tr><th>Bron</th><th>Bereik</th><th>Beoordeling</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.title)+'</td><td>'+esc(layers[r.layer])+'</td><td>'+(r.demo?'Geen echte inhoud':'Nog niet professioneel beoordeeld')+'</td></tr>').join('')+'</tbody></table></div></div>':'');
}
function modulePage(){return heading('MODULAIRE WERKPLEK','Aansluiten zonder alles te verbouwen.','Bronnen en applicaties krijgen een eigen modulekaart. Een vaste link opent de externe toepassing zonder patiënt- of zoekgegevens.')+
 '<div class="grid">'+modules.map(m=>'<article class="card"><span class="badge teal">'+(m.kind==='source-library'?'Actieve bronlaag':'Externe link')+'</span><h3>'+esc(m.name)+'</h3><p>'+(m.id==='groningen'?'Eerdere inventaris van 4.627 bronverwijzingen; inclusief contexten, toegangsstatus en bronrelaties.':m.kind==='source-library'?'Een vakgebied binnen dezelfde gedeelde catalogus. Gegevens staan los van de schermen en kunnen via een gecontroleerde release worden bijgewerkt.':'Opent het bestaande oncologieprototype. Geen gegevensuitwisseling of accountkoppeling geïmplementeerd.')+'</p><div class="card-bottom">'+(m.id==='groningen'?'<a href="#groningen">Open Groningse bronbibliotheek</a>':specialties[m.id]?'<button data-specialty="'+m.id+'">Open '+esc(m.name)+'</button>':external(m.url,'Open toepassing'))+'<div class="actions"><button data-manifest="'+m.id+'">Bekijk modulecontract</button></div></div></article>').join('')+
 '<article class="card local"><span class="badge">Aansluitbaar model</span><h3>Andere Inforium- en CHIP-modules</h3><p>Notes, regionale afspraken, patiëntenbibliotheken en externe toepassingen kunnen aansluiten via hetzelfde bron- en modulecontract. Deze koppelingen zijn nog niet gerealiseerd.</p><button id="contract">Bekijk aansluitroute</button></article></div>'+
 '<div class="panel"><h2>Van bron naar werkvloer</h2><div class="steps"><div class="step"><strong>01 · Bronadapter</strong>Leest toegestane bronmetadata</div><div class="step"><strong>02 · Bronregister</strong>Versie, eigenaar en herkomst</div><div class="step"><strong>03 · Redactie</strong>Controle op inhoud en bereik</div><div class="step"><strong>04 · Chipboard</strong>Vinden, combineren en openen</div></div><p>Deze versie gebruikt lokale JSON-bestanden. Een centrale catalogus-API, authenticatie voor redacteuren en automatische bronadapters zijn vervolgbouw.</p></div>';}
function management(){
 const statuses=['idle','detected','staged','reviewed','released'], pos=statuses.indexOf(update);
 return heading('BRONNEN & UPDATES','Actueel houden, met controle ertussen.','Publicatie, geldigheidsbeoordeling en raadpleging zijn afzonderlijke datums. Een nieuwe datum is geen nieuwe medische goedkeuring.')+
 '<div class="panel"><div class="section-row"><h2>Probeer een bronwijziging</h2><span class="badge demo">Simulatie · alleen in dit scherm</span></div><p>Doorloop de beheerroute met fictieve metadata. De echte bronrecords worden niet gewijzigd.</p><div class="steps">'+['Wijziging gevonden','Conceptversie','Redactie gecontroleerd','Versie vrijgegeven'].map((s,i)=>'<div class="step '+(pos>i?'done':'')+'"><strong>'+('0'+(i+1))+'</strong>'+s+'</div>').join('')+'</div><p id="update-status" role="status">'+[
  'Start een fictieve wijziging om de vervolgstappen te bekijken.',
  'Een fictieve nieuwe bronversie is gevonden. De huidige catalogus blijft beschikbaar.',
  'Conceptversie klaar. Vergelijking: versie 1 → versie 2; fictieve wijziging in contactgegevens. Inhoud, hergebruik en gekoppelde kaarten moeten worden gecontroleerd.',
  'Democontrole afgerond. In productie is een bevoegde redacteur met vastgelegde identiteit vereist.',
  'Demoversie vrijgegeven. In productie volgt een geteste release; eerdere versies blijven via Git beschikbaar.'
 ][pos]+'</p><div class="actions">'+(update==='idle'?'<button id="detect" class="primary">Simuleer bronwijziging</button>':update!=='released'?'<button id="advance" class="primary">'+({detected:'Maak democoncept',staged:'Simuleer redactionele controle',reviewed:'Geef demoversie vrij'}[update])+'</button>':'')+'<button id="reset-update">Herstart demonstratie</button></div></div>'+
 '<div class="panel"><h2>Bronregister</h2><p>'+sources.length+' bronverwijzingen, inclusief 3 algemene verwijzingen uit de overdracht. De catalogus bevat '+catalog.length+' aanvullende bronkaarten. Laatst opnieuw geraadpleegde modulemetadata: 4 oktober 2026.</p><div class="table-wrap"><table><thead><tr><th>Bron</th><th>Publicatie</th><th>Geldigheid beoordeeld</th><th>Raadpleging</th></tr></thead><tbody>'+sources.map(s=>'<tr><td>'+external(s.url,s.title)+'<small>Geen professionele goedkeuring van afgeleide records</small></td><td>'+date(s.published_at)+'</td><td>'+date(s.validity_assessed_at)+'</td><td>'+date(s.checked_at)+'</td></tr>').join('')+'</tbody></table></div></div><div class="panel"><h2>Als een bron verandert of niet opent</h2><p>Behoud de laatst gecontroleerde versie en datum. Zet hercontrole uit bij de eigenaar. Een technische fout bewijst niet dat medische informatie vervallen is. Het meegeleverde controlescript maakt een bereikbaarheidsrapport en wijzigt geen inhoud of goedkeuringsstatus.</p></div>';
}
function scope(){return heading('GEBRUIK & AFBAKENING','Een bronnenwerkplek voor professionals.','Dit prototype onderzoekt het vinden en combineren van kennis. Het is niet gereed voor klinische inzet.')+
 '<div class="two-columns"><section class="panel"><h2>Wat deze versie doet</h2><ul class="scope-list"><li>Bibliotheekmetadata filteren op onderwerp, taak en brontype.</li><li>Herleidbare bronkaarten naast elkaar tonen.</li><li>Vaste externe links openen zonder contextoverdracht.</li><li>Een modulaire structuur en beheerroute demonstreren.</li></ul></section><section class="panel"><h2>Grenzen van deze versie</h2><ul class="scope-list"><li>Alleen algemene zoektrefwoorden; geen patiëntgegevens, dossiers, uploads of vrije notities.</li><li>Geen diagnose, triage, dosering of gepersonaliseerde aanbeveling.</li><li>Geen taalmodel of gegenereerde medische antwoorden.</li><li>Geen professionele validatie van de drie voorbeeldrecords.</li></ul></section></div>'+
 '<div class="panel"><h2>MDR: ontwerpkeuze, geen vrijstelling</h2><p>Het ontbreken van patiëntgegevens of generatieve AI garandeert niet dat software buiten de MDR valt. Beoogd gebruik, functies en hun samenhang zijn bepalend. Ook zoeken kan een medisch doel dienen. Nieuwe functies en modulecombinaties vragen daarom een kwalificatiebeoordeling vóór klinische inzet.</p>'+external('https://health.ec.europa.eu/document/download/b45335c5-1679-4c71-a91c-fc7a4d37f12b_en?filename=md_mdcg_2019_11_guidance_qualification_classification_software_en.pdf','MDCG 2019-11 rev.1 · juni 2025')+'</div><div class="panel"><h2>Gegevens & herkomst</h2><p>Zoektrefwoorden, filters en bordselecties blijven alleen in paginageheugen. Zoekopdrachten worden niet in de URL gezet, opgeslagen of verstuurd. Er zijn geen analytics, cookies, externe lettertypen of AI-aanroepen toegevoegd. De hostingprovider ontvangt gewone webverzoeken; externe websites hanteren hun eigen privacybeleid.</p><p>Basis: Inforium_Richtlijnen_Codex_Overdracht.zip, versie 4 oktober 2026. De bronkaarten zijn beperkte redactionele voorbeelden. Daarnaast is de eerdere Groningse inventaris van 3 oktober 2026 gekoppeld. Geen volledige of opnieuw inhoudelijk gecontroleerde database of regionale afsprakenbank.</p></div>';
}

function groningenPage(){
 const rows=filterGroningen(groningenRecords,groningenFilters),pages=Math.max(1,Math.ceil(rows.length/12));groningenPageIndex=Math.min(groningenPageIndex,pages-1);
 const groups=Object.fromEntries([...new Set(groningenRecords.flatMap(r=>r.contexts.map(c=>c.group)))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'nl')).map(v=>[v,v]));
 const paths=Object.fromEntries(groningenRecords.flatMap(r=>r.contexts).filter(c=>(!groningenFilters.group||c.group===groningenFilters.group)&&c.path).map(c=>[c.path,c.pathology]));
 return heading('BRONBIBLIOTHEEK · UMCG','Medische Oncologie Groningen','De eerdere inventaris, verbonden met je Chipboard. Landelijke richtlijnen en Groningse bronnen blijven afzonderlijk herkenbaar.')+
 '<div class="notice">Inventaris van 3 oktober 2026 · geen nieuwe inhoudelijke controle. Studie- en toegangsstatussen zijn momentopnamen. Controleer de actuele informatie altijd bij de bron.</div>'+
 '<div class="stats"><span><strong>'+groningenRecords.length.toLocaleString('nl-NL')+'</strong>verwijzingen</span><span><strong>'+groningenRecords.filter(r=>r.locked).length.toLocaleString('nl-NL')+'</strong>alleen metadata / inloggen</span><span><strong>'+groningenRecords.filter(r=>r.external).length+'</strong>externe verwijzingen</span></div>'+
 '<div class="searchbox"><div class="filters"><label>Voor wie<select id="g-audience">'+options({patient:'Patiënt',professional:'Professional',unknown:'Niet vastgesteld'},groningenFilters.audience,'Iedereen')+'</select></label><label>Soort informatie<select id="g-kind">'+options(groningenKinds,groningenFilters.kind,'Alle soorten')+'</select></label><label>Tumorgroep<select id="g-group">'+optionsSafe(groups,groningenFilters.group,'Alle groepen')+'</select></label><label>Tumortype<select id="g-path">'+optionsSafe(paths,groningenFilters.path,'Alle tumortypen')+'</select></label><button id="g-reset">Wis filters</button></div></div>'+
 '<div class="section-row"><h2>Groningse bronverwijzingen</h2><span class="count" role="status">'+rows.length+' resultaten · pagina '+(groningenPageIndex+1)+' van '+pages+'</span></div><div class="grid">'+(rows.length?rows.slice(groningenPageIndex*12,(groningenPageIndex+1)*12).map(r=>card(r)).join(''):'<div class="empty"><h3>Geen verwijzingen voor deze combinatie</h3><p>Wis een filter om andere bronnen te bekijken.</p></div>')+'</div><div class="actions"><button id="g-prev" '+(groningenPageIndex===0?'disabled':'')+'>Vorige pagina</button><button id="g-next" '+(groningenPageIndex+1>=pages?'disabled':'')+'>Volgende pagina</button></div>';
}
function optionsSafe(dict,current,all){return '<option value="">'+esc(all)+'</option>'+Object.entries(dict).sort((a,b)=>a[1].localeCompare(b[1],'nl')).map(([v,label])=>'<option value="'+esc(v)+'" '+(current===v?'selected':'')+'>'+esc(label)+'</option>').join('');}
function groningenDetails(r){
 const studyStatus={open:'Open in de inventaris',closed:'Gesloten in de inventaris',hold:'On hold in de inventaris',unknown:'Niet vermeld'};
 return '<div class="notice">UMCG-broninventaris van 3 oktober 2026; geen landelijke richtlijn en geen nieuwe professionele goedkeuring. '+(r.locked?'Alleen metadata beschikbaar; inloggen bij de bron kan nodig zijn.':'De actuele broninhoud en toegang zijn hier niet opnieuw vastgesteld.')+'</div>'+
 '<dl><dt>Categorie / doelgroep volgens inventaris</dt><dd>'+esc(groningenKinds[r.kind])+' / '+esc({patient:'Patiënt',professional:'Professional',unknown:'Onbekend'}[r.audience]||r.audience)+'</dd>'+
 (r.kind==='study'?'<dt>Studiestatus op inventarisdatum</dt><dd>'+esc(studyStatus[r.status]||r.status||'Onbekend')+' · controleer actuele status bij de bron</dd>':'')+
 '<dt>Broncode / bronversie</dt><dd>'+esc(r.code||'Niet vermeld')+' / '+esc(r.sourceVersion||'Niet vermeld')+'</dd><dt>Wijzigingsdatum uit eerdere inventaris</dt><dd>'+esc(r.modified||'Niet vermeld')+' · geen medische beoordelingsdatum</dd><dt>Bestemming</dt><dd>'+esc(new URL(r.url).hostname)+(r.external?' · externe website':'')+'</dd></dl>'+
 '<h3>Broncontexten uit eerdere inventaris</h3><p>De combinaties hieronder komen uit de inventaris; ze zijn geen patiëntselectie of behandeladvies.</p>'+ (r.contexts.length?'<div class="table-wrap"><table><thead><tr><th>Tumorgroep</th><th>Tumortype</th><th>Context</th><th>Status destijds</th></tr></thead><tbody>'+r.contexts.map(c=>'<tr><td>'+esc(c.group)+'</td><td>'+esc(c.pathology)+'</td><td>'+esc(c.phase||'Niet vermeld')+'</td><td>'+esc(c.status||'Niet vermeld')+'</td></tr>').join('')+'</tbody></table></div>':'<p>Geen specifieke context vastgelegd.</p>')+
 external(r.url,r.locked?'Open bron · mogelijk inloggen':'Open oorspronkelijke bron','source-link')+
 (r.related.length?'<h3>Gekoppelde bronnen in de inventaris</h3><p>Oorspronkelijke relaties; geen automatische aanbeveling.</p><div class="related">'+r.related.map(id=>{const other=groningenRecords.find(x=>x.id===id);return '<button data-related="'+id+'">'+esc(other.title)+'</button>';}).join('')+'</div>':'');
}


let searchIndex=[],searchQuery='',searchPage=0,searchProvider='',searchComplete=false;
function searchPageView(){
 const response=searchResources(searchIndex,searchQuery,{provider:searchProvider,completeOnly:searchComplete}),rows=response.results;
 const pages=Math.max(1,Math.ceil(rows.length/12));searchPage=Math.min(searchPage,pages-1);
 const full=rows.filter(r=>r.matched===r.total).length;
 let resultHtml='',previous='';
 for(const hit of rows.slice(searchPage*12,(searchPage+1)*12)){
  const group=hit.matched===hit.total?'Alle trefwoorden gevonden':'Een deel van de trefwoorden gevonden';
  if(group!==previous){resultHtml+='<h2 class="search-group">'+group+'</h2>';previous=group;}
  resultHtml+=card(hit.record,false,hit);
 }
 return heading('ALGEMEEN ZOEKEN','Zoek over alle aangesloten bronnen.','Eén zoekopdracht in de richtlijnselectie en de Groningse inventaris. De grootste trefwoordovereenkomst staat vooraan.')+
 '<p class="search-scope">'+searchIndex.length.toLocaleString('nl-NL')+' bronkaarten doorzoekbaar · titels, codes, onderwerpen, broncontexten en gekoppelde titels. Geen volledige documentteksten of live internetzoekactie.</p>'+
 '<div class="searchbox"><div class="filters search-filters"><label>Broncollectie<select id="search-provider">'+options({national:'Landelijke richtlijnselectie',groningen:'Oncologie Groningen'},searchProvider,'Alle aangesloten bronnen')+'</select></label><label class="toggle"><input id="search-complete" type="checkbox" '+(searchComplete?'checked':'')+'>Alle trefwoorden moeten overeenkomen</label><button id="search-clear">Wis zoekopdracht</button></div><details class="ranking-help"><summary>Hoe wordt de volgorde bepaald?</summary><p>Eerst het aantal verschillende gevonden trefwoorden. Daarna de plek: broncode en titel tellen zwaarder dan broncontext of een gekoppelde titel. Een exacte titel of woordgroep krijgt extra gewicht. Woordbegin en enkele expliciet vermelde zoekverwanten tellen minder zwaar dan exacte woorden. Gelijke resultaten staan op titelvolgorde.</p><p>De volgorde drukt tekstovereenkomst uit, geen medische geschiktheid, kwaliteit of actualiteit. Bronstatussen blijven apart zichtbaar. Zoekverwanten zijn redactionele zoekhulpen, geen gelijkstelling van medische begrippen.</p></details></div>'+
 (response.error?'<div class="notice" role="alert">'+esc(response.error)+'</div>':!response.terms.length?'<div class="empty"><h2>Vul bovenaan enkele trefwoorden in</h2><p>Bijvoorbeeld “borstkanker radiotherapie”, “neus anamnese” of een broncode. Gebruik algemene trefwoorden, geen patiëntgegevens.</p></div>':
 '<div class="section-row"><h2>Resultaten voor “'+esc(searchQuery)+'”</h2><span class="count" role="status">'+rows.length+' resultaten · '+full+' met alle trefwoorden · pagina '+(searchPage+1)+' van '+pages+'</span></div>'+
 (rows.length?'<div class="grid">'+resultHtml+'</div><div class="actions"><button id="search-prev" '+(searchPage===0?'disabled':'')+'>Vorige pagina</button><button id="search-next" '+(searchPage+1>=pages?'disabled':'')+'>Volgende pagina</button></div>':'<div class="empty"><h3>Geen trefwoordovereenkomst gevonden</h3><p>Probeer minder of andere woorden, of kies alle broncollecties. De catalogus bevat niet alle medische informatie. Er wordt geen antwoord gegenereerd.</p></div>'));
}
function searchReason(hit){
 return '<section class="match search-reasons" aria-label="Waarom gevonden"><p><b>Waarom gevonden</b></p><strong>'+hit.matched+' van '+hit.total+' trefwoorden gevonden</strong>'+
 (hit.phraseBonus?'<p>Exacte woordgroep in de titel telt extra mee.</p>':'')+
 '<ul>'+hit.matches.map(m=>'<li><b>'+esc(m.term)+'</b> · '+esc(m.field)+(m.mode==='alias'?' · zoekverwant: '+esc(m.alias):m.mode==='prefix'?' · woordbegin':'')+'<span>“'+esc(m.snippet)+'”</span></li>').join('')+'</ul>'+
 (hit.missing.length?'<p>Niet gevonden: '+hit.missing.map(esc).join(', ')+'</p>':'')+'</section>';
}
document.addEventListener('submit',e=>{
 if(e.target.id!=='global-search')return;
 e.preventDefault();searchQuery=$('#global-query').value.trim();searchPage=0;
 location.hash='zoeken';render();$('#main').focus();
});

function render(){
 const page=location.hash.slice(1)||'bibliotheek';
 const views={zoeken:searchPageView,bibliotheek:library,groningen:groningenPage,board,modules:modulePage,beheer:management,kaders:scope};
 $('#main').innerHTML=(views[page]||library)();
 document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===page; a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 $('#board-count').textContent=selected.size;
}
function showDialog(html){$('#detail-body').innerHTML=html;$('#detail').showModal();}
function showResource(id){
 const r=resources.find(r=>r.id===id); if(!r)return;
 let html='<div class="dialog-top"><span class="badge '+(r.demo?'demo':'warning')+'">'+(r.demo?'Demonstratie':'Redactioneel te beoordelen')+'</span><button class="close" data-close>Sluiten ✕</button></div><h2 id="detail-title">'+esc(r.title)+'</h2><p>'+esc(r.description)+'</p>';
 if(r.groningen){html+=groningenDetails(r);}
 else if(r.navigation){html+='<div class="notice">Alleen bronnavigatie. Geen samenvatting, behandeladvies of professionele inhoudelijke goedkeuring.</div><dl><dt>Type pagina</dt><dd>'+esc(r.source_kind==='overview'?'Richtlijnoverzicht; onderliggende modules niet automatisch opgenomen':'Afzonderlijke richtlijnmodule')+'</dd><dt>Vindbaar vanuit</dt><dd>'+r.specialties.map(k=>esc(specialties[k])).join(', ')+'</dd><dt>Publicatie</dt><dd>'+date(r.published_at)+'</dd><dt>Geldigheid beoordeeld volgens de bron</dt><dd>'+date(r.validity_assessed_at)+'</dd><dt>Titel, URL en metadata geraadpleegd</dt><dd>'+date(r.checked_at)+'</dd><dt>Catalogusversie</dt><dd>'+esc(r.version)+'</dd><dt>Hergebruik</dt><dd>'+esc(r.rights)+'</dd></dl>'+external(r.url,'Open oorspronkelijke bron','source-link');}
 else if(r.demo) html+='<div class="notice">Geen echte afspraak of patiënteninformatie. Dit is een invulmodel voor een toekomstige bronkoppeling.</div><dl><dt>Type</dt><dd>'+esc(layers[r.layer])+'</dd><dt>Benodigde brongegevens</dt><dd>Eigenaar, regio, doelgroep, originele URL, versie, geldigheidsperiode, hergebruikrechten en redactionele controle.</dd><dt>Relatie tot landelijke bronnen</dt><dd>Aanvulling, afwijking of procesafspraak expliciet vastleggen; nooit stilzwijgend samenvoegen.</dd></dl>';
 else {
 const a=r.record,s=r.source;
 const labels={suspected_condition:'Toepassingsgebied: mogelijke luchtwegallergie',setting:'Setting: tweede / derde lijn',age_group:'Doelgroep: kinderen'};
 html+='<div class="notice">'+(a.record_type==='navigation_only'?'Uitsluitend bronnavigatie; geen zelfstandige diagnostische beslisregel.':'Deze kaart beschrijft een bronpassage, niet wat bij een individuele patiënt moet gebeuren.')+'</div><dl><dt>Inforium Notes · toepassingsgebied van de bron</dt><dd>'+(a.applicability.any_of.map(g=>g.all_of.map(c=>esc(labels[c.field]||c.field)).join(' én ')).filter(Boolean).join(' OF ') || 'Niet als zelfstandig criterium gemodelleerd')+'</dd><dt>Uitsluitingen</dt><dd>Niet volledig geïnventariseerd. Geen claim van volledige toepasbaarheid.</dd><dt>Bronsectie</dt><dd>'+esc(a.source_section)+'</dd><dt>Officiële aanbeveling</dt><dd>Lees in de oorspronkelijke module; niet volledig overgenomen.</dd><dt>Onderbouwing en overwegingen</dt><dd>Afzonderlijke secties in de bron. Lees samen met de aanbeveling.</dd><dt>Aanbevelingsmodaliteit in overdracht</dt><dd>'+esc({do:'Doen · beperkte redactionele interpretatie',not_applicable:'Niet van toepassing'}[a.modality]||a.modality)+'</dd><dt>Bewijszekerheid</dt><dd>Niet vastgelegd in het actierecord; geen GRADE-niveau toegekend.</dd><dt>Redactionele notitie</dt><dd>'+esc(a.review_note)+'</dd><dt>Publicatie / geldigheid beoordeeld</dt><dd>'+date(s.published_at)+' / '+date(s.validity_assessed_at)+'</dd><dt>Raadpleging in overdracht</dt><dd>'+date(s.checked_at)+'</dd></dl>'+external(s.url,'Open oorspronkelijke module','source-link')+'<p class="muted">Opent de bron niet? De status is dan onbekend; behoud de laatste controledatum en laat de bron opnieuw controleren.</p>';
 }
 showDialog(html);
}
document.addEventListener('click',event=>{
 const button=event.target.closest('button');if(!button)return;
 if(button.id==='search-clear'){searchQuery='';$('#global-query').value='';searchPage=0;render();$('#global-query').focus();}
 if(button.id==='search-prev'||button.id==='search-next'){searchPage+=button.id==='search-next'?1:-1;render();$('#main').focus();}
 if(button.dataset.related){$('#detail').close();showResource(button.dataset.related);}
 if(button.id==='g-reset'){Object.assign(groningenFilters,{audience:'',kind:'',group:'',path:''});groningenPageIndex=0;render();$('#g-audience').focus();}
 if(button.id==='g-prev'||button.id==='g-next'){groningenPageIndex+=button.id==='g-next'?1:-1;render();$('#'+button.id).focus();}
 if(button.hasAttribute('data-close')) $('#detail').close();
 if(button.dataset.open)showResource(button.dataset.open);
 if(button.dataset.pin){const id=button.dataset.pin;selected.has(id)?selected.delete(id):selected.add(id);render();document.querySelector('[data-pin="'+id+'"]')?.focus();toast(selected.has(id)?'Bron toegevoegd aan je Chipboard':'Bron verwijderd van je Chipboard');}
 if(button.dataset.specialty){Object.assign(filters,{specialty:button.dataset.specialty,topic:'',task:'',layer:''});location.hash='bibliotheek';render();$('#specialty').focus();}
 if(button.id==='reset'){Object.assign(filters,{specialty:'',topic:'',task:'',layer:'',demo:false});render();$('#topic').focus();}
 if(button.id==='clear-board'){selected.clear();render();$('#clear-board').focus();toast('Chipboard leeggemaakt');}
 if(['detect','advance','reset-update'].includes(button.id)){update=stageUpdate(update,button.id==='detect'?'detect':button.id==='advance'?'advance':'reset');render();($('#advance')||$('#reset-update')).focus();}
 if(button.dataset.manifest){const m=modules.find(m=>m.id===button.dataset.manifest);showDialog('<div class="dialog-top"><span class="badge">Modulecontract v1</span><button data-close>Sluiten ✕</button></div><h2 id="detail-title">'+esc(m.name)+'</h2><p>Dit manifest beschrijft alleen de module, de vaste bestemming en toegestane functies.</p><pre>'+esc(JSON.stringify(m,null,2))+'</pre>');}
 if(button.id==='contract')showDialog('<div class="dialog-top"><span class="badge">Aansluitroute</span><button data-close>Sluiten ✕</button></div><h2 id="detail-title">Een module toevoegen</h2><ol class="scope-list"><li>Leg eigenaar, bronrechten en beoogd gebruik vast.</li><li>Voeg een manifest toe aan data/modules.json met vaste HTTPS-link en patientData: false.</li><li>Map bronmetadata naar een eigen adapter; behoud versie en herkomst.</li><li>Laat inhoud en modulecombinatie beoordelen.</li><li>Valideer, test en publiceer een nieuwe versie via GitHub.</li></ol><p>Een link is nog geen API-integratie. Uitwisseling en authenticatie vereisen aanvullende bouw en toetsing.</p>');
});
document.addEventListener('change',e=>{
 if(e.target.id==='search-provider'){searchProvider=e.target.value;searchPage=0;render();$('#search-provider').focus();}
 if(e.target.id==='search-complete'){searchComplete=e.target.checked;searchPage=0;render();$('#search-complete').focus();}
 if(e.target.id.startsWith('g-')){const key=e.target.id.slice(2);if(Object.hasOwn(groningenFilters,key)){groningenFilters[key]=e.target.value;if(key==='group')groningenFilters.path='';groningenPageIndex=0;render();$('#g-'+key).focus();}}
 if(e.target.id==='specialty'){Object.assign(filters,{specialty:e.target.value,topic:'',task:''});render();$('#specialty').focus();}
 if(['topic','task','layer'].includes(e.target.id)){const id=e.target.id;filters[id]=e.target.value;render();$('#'+id).focus();}
 if(e.target.id==='demo'){filters.demo=e.target.checked;render();$('#demo').focus();}
});
window.addEventListener('hashchange',()=>{render();$('#main').focus();});
try {
 [sources,actions,modules,catalog,groningenPayload]=await Promise.all([read('./data/bronnen.json'),read('./data/voorbeeldacties.json'),read('./data/modules.json'),read('./data/catalogus.json'),read('./data/groningen.json')]);
 sources=[...sources,...catalog];
 modules.forEach(validateManifest); groningenRecords=decodeGroningen(groningenPayload); resources=[...makeResources(),...groningenRecords];searchIndex=buildSearchIndex(resources,{topics,specialties,tasks,kinds:groningenKinds});render();
} catch(error){$('#main').innerHTML='<div class="empty"><h1>De brongegevens konden niet worden geladen.</h1><p>Er worden geen vervangende antwoorden getoond. Probeer de pagina opnieuw te laden.</p><a href="./">Opnieuw laden</a></div>';console.error(error);}
