import {filterTumorContexts,tumorFilters} from './tumor-search.js';
import {ONCO_COLLECTIONS,validateOncology,oncologyHome,oncologyRegister} from './oncology.js';
import {JGZ_COLLECTIONS,JGZ_KNOWLEDGE,validateJgzLibrary,jgzHome,jgzRegister,jgzNews} from './jgz.js';
import {decodeExtraSources,mergeSourceImports,LANGUAGE_LABELS} from './extra-sources.js';
import {patientActions,patientLink,sharingDialog} from './patient-sharing.js';
import {decodePatientSources} from './patient-sources.js';
import {decodePrimaryGuidelines} from './primary-guidelines.js';
import {decodeInforium,integratedCard,integratedHome,inforiumDetails,packagePreview} from './integrated.js';
import {decorateCompact} from './icons.js';
import {compactCard,compactSearch,sourceUrl} from './compact.js';
import {refineResults,kindOf} from './refine.js';
import {decodePznl} from './pznl.js';
import {buildSearchIndex,searchResources,SOURCE_COLLECTIONS,collectionOf} from './search.js';
import {decodeGroningen,filterGroningen,groningenKinds} from './groningen.js';
import {filterResources, validateManifest, stageUpdate} from './core.js';
const compactMode=document.body.dataset.view==='compact';
const integratedMode=document.body.dataset.experience==='inforium';
const oncologyMode=document.body.dataset.edition==='oncology';
const jgzMode=['jgz','oncology'].includes(document.body.dataset.edition);
if(jgzMode){for(const key of Object.keys(SOURCE_COLLECTIONS))delete SOURCE_COLLECTIONS[key];Object.assign(SOURCE_COLLECTIONS,oncologyMode?ONCO_COLLECTIONS:JGZ_COLLECTIONS);}
if(integratedMode&&!jgzMode)SOURCE_COLLECTIONS.inforium='Inforium Advanced · voorbeelden';
let inforiumRecords=[],iaAge='';
let compactType='',compactFiltersOpen=false,compactHits=new Map();
const $ = selector => document.querySelector(selector);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = s => s ? new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeZone:'UTC'}).format(new Date(s)) : 'Niet vastgelegd';
const layers = {nhg:'NHG · Richtlijnen',ncj:'NCJ · JGZ-richtlijnen',inforium:'Inforium · ontwerpvoorbeeld',pznl:'PZNL · Palliatieve zorg',groningen:'Groningen · broninventaris',national:'Landelijke richtlijn',local:'Lokale afspraak',regional:'Regionaal / transmuraal',patient:'Patiënteninformatie',social:'Sociaal domein'};
const specialties = {kno:'KNO',cardiologie:'Cardiologie',oncologie:'Oncologie',radiotherapie:'Radiotherapie'};
const topics = {neus:'Neusklachten',duizeligheid:'Duizeligheid',gehoor:'Gehoorverlies','hoofd-hals':'Hoofd-halstumoren',atriumfibrilleren:'Atriumfibrilleren',hartrevalidatie:'Hartrevalidatie',borstkanker:'Borstkanker',longkanker:'Longcarcinoom'};
const tasks = {overview:'Richtlijnoverzicht',history:'Anamnese',diagnostics:'Diagnostiek',referral:'Verwijzen & samenwerken',shared_decision:'Informeren & samen beslissen',followup:'Opvolgen',urgency:'Urgentie',examination:'Lichamelijk onderzoek',treatment:'Behandeling'};
const filters = {specialty:'',topic:'',task:'',layer:'',demo:false};
let pznlPayload,pznlRecords=[],groningenPayload,groningenRecords=[],groningenPageIndex=0;
const groningenFilters={audience:'patient',kind:'',group:'',path:''};
let catalog=[], sources=[], actions=[], modules=[], resources=[], selected=new Set(), update='idle', toastTimer;
const favoriteKey=oncologyMode?'chipboard-oncology-favorites-v1':'chipboard-jgz-favorites-v1';
let favorites={cards:[],packages:[]};
if(jgzMode){try{const saved=JSON.parse(localStorage.getItem(favoriteKey));if(saved&&Array.isArray(saved.cards)&&Array.isArray(saved.packages)){favorites.cards=saved.cards.filter(x=>typeof x==='string');favorites.packages=saved.packages.filter(x=>x&&typeof x.id==='string'&&Array.isArray(x.cards)).map(x=>({id:x.id,name:typeof x.name==='string'?x.name.slice(0,80):'',cards:x.cards.filter(id=>typeof id==='string')}));}}catch{}}
function saveFavorites(next){try{localStorage.setItem(favoriteKey,JSON.stringify(next));favorites=next;return true;}catch{toast('Opslaan lukt niet. Sta lokale browseropslag toe.');return false;}}
function favoritesPage(){
 const rows=resources.filter(r=>favorites.cards.includes(r.id));
 return '<h1>Mijn Favorieten</h1><p>Opgeslagen in deze browser, alleen bronverwijzingen. Werkpakketten bevatten geen patiëntgegevens. Niet gesynchroniseerd met andere apparaten.</p><h2>Werkpakketten</h2><div class="compact-grid">'+(favorites.packages.map((p,i)=>{const known=resources.filter(r=>p.cards.includes(r.id));return '<article class="compact-card"><h3>'+esc(p.name||'Werkpakket '+(i+1))+'</h3><p>'+known.length+' bronnen</p><p>'+known.slice(0,3).map(r=>esc(r.title)).join(' · ')+'</p>'+(known.length<p.cards.length?'<p>Een of meer opgeslagen bronnen zijn niet meer beschikbaar.</p>':'')+'<div class="actions"><button data-restore-package="'+esc(p.id)+'">Toevoegen aan werkmap</button><button data-remove-package="'+esc(p.id)+'">Verwijderen</button></div></article>';}).join('')||'<p>Nog geen werkpakket opgeslagen. Stel er een samen in Mijn werkmap.</p>')+'</div><h2>Bronnen</h2><div class="compact-grid">'+(rows.map(r=>card(r)).join('')||'<p>Nog geen favoriete bronnen. Open een bronkaart en kies Opslaan in Favorieten.</p>')+'</div>';
}
const read = async path => { const response=await fetch(path); if(!response.ok) throw new Error('Gegevens niet bereikbaar'); return response.json(); };
function toast(message){ $('#toast').textContent=message; $('#toast').classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800); }
const external = (url,label,cls='') => '<a class="'+cls+'" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+' ↗</a>';
function makeResources(){
 const real=actions.map(a=>({id:a.id,title:a.title,description:a.record_type==='navigation_only'?'Verwijzing naar de bron over positionele downbeatnystagmus. Geen zelfstandige diagnostische regel.':'Bronpassage over '+(a.id==='allergy-child-history'?'anamnese bij kinderen binnen de allergiemodule.':'anamnese binnen de module luchtwegallergie.'),topics:[a.source_id==='bppd-anterior'?'duizeligheid':'neus'],tasks:[a.action],layer:'national',specialties:['kno'],demo:false,source:sources.find(s=>s.id===a.source_id),record:a,owner:'Richtlijnendatabase · initiatief NVKNO',version:'Overdracht 04-10-2026'}));
 const examples=[
  ['demo-local','Lokale werkafspraak','Plaats voor een lokale procesafspraak met eigenaar, bereik en revisiedatum. Er is nog geen echte afspraak aangeleverd.','local',['history','referral']],
  ['demo-region','Samenwerkingsafspraak in de regio','Laat een regionale of transmurale bron naast de landelijke richtlijn zien. Deze voorbeeldkaart bevat geen verwijscriteria.','regional',['referral','followup']],
  ['demo-patient','Informatie om samen te bespreken','Plaats voor een specifiek gecontroleerde patiëntenbron. Er is nog geen gekoppelde patiëntenfolder beschikbaar.','patient',['shared_decision']],
  ['demo-social','Ondersteuning in het sociaal domein','Plaats voor een geverifieerde gemeentelijke of welzijnsbron. Contacten, bereik en toegangsvoorwaarden moeten nog worden aangeleverd.','social',['referral','followup']]
 ].map(([id,title,description,layer,t])=>({id,title,description,specialties:Object.keys(specialties),topics:Object.keys(topics),tasks:t,layer,demo:true,owner:'Demonstratie · geen echte organisatie',version:'Modelvoorbeeld v0.1'}));
 const added=catalog.map(c=>({...c,source:c,description:(c.source_kind==='overview'?'Startpagina met toegang tot de oorspronkelijke richtlijnmodules.':'Verwijzing naar de oorspronkelijke richtlijnmodule.')+' Lees de inhoud en voorwaarden bij de bron.',layer:'national',demo:false,owner:'Richtlijnendatabase',navigation:true}));
 return [...real,...added,...examples];
}
function heading(kicker,title,description,extra=''){return '<div class="heading"><div><div class="eyebrow">'+kicker+'</div><h1>'+title+'</h1><p class="intro">'+description+'</p></div>'+extra+'</div>';}
function card(r,board=false,hit=null){if(integratedMode)return integratedCard(r,selected,hit).replace('</article>',(jgzMode?'<div class="actions"><button data-favorite="'+esc(r.id)+'">'+(favorites.cards.includes(r.id)?'★ In Favorieten':'☆ Opslaan in Favorieten')+'</button></div>':'')+'</article>');if(compactMode)return compactCard(r,selected,hit);return '<article class="card '+(r.layer==='social'?'social':r.layer==='patient'?'patient':r.layer!=='national'?'local':'')+'"><div><span class="badge '+(r.demo?'demo':'')+'">'+esc(layers[r.layer])+'</span></div><h3>'+esc(r.title)+'</h3><div class="meta">'+esc(r.owner)+'</div><p>'+esc(r.description)+'</p><div class="card-bottom"><div class="tags">'+[...(r.specialties||[]).map(k=>'<span>'+specialties[k]+'</span>')].join('')+r.tasks.map(t=>'<span>'+tasks[t]+'</span>').join('')+'</div><span class="badge '+(r.demo?'demo':'warning')+'">'+(r.demo?'Demonstratie · geen broninhoud':r.pznl||r.primaryGuideline||r.patientImport?esc(r.kind)+' · bronverwijzing':r.groningen?(r.locked?'Alleen metadata · mogelijk inloggen':'Inventaris 03-10-2026 · bronverwijzing'):r.navigation?(r.source_kind==='overview'?'Richtlijnoverzicht · bronverwijzing':'Richtlijnmodule · bronverwijzing'):'Redactioneel te beoordelen')+'</span><div class="actions"><button data-open="'+r.id+'">Bekijk bronkaart</button><button data-pin="'+r.id+'" class="'+(selected.has(r.id)?'saved':'')+'">'+(selected.has(r.id)?'✓ Op Chipboard':'+ Chipboard')+'</button></div>'+(hit?searchReason(hit):'')+'<div class="match">'+(board?'Afzonderlijke bron · '+esc(r.version):'Bronnavigatie · geen beoordeling van patiëntgeschiktheid.')+'</div>'+patientActions(r)+'</div></article>';}
function options(dict,current,all){return '<option value="">'+all+'</option>'+Object.entries(dict).map(([v,label])=>'<option value="'+v+'" '+(current===v?'selected':'')+'>'+label+'</option>').join('');}
function library(){
 const found=filterResources(resources.filter(r=>!r.groningen&&!r.pznl&&!r.primaryGuideline&&!r.patientImport),filters);
 return heading('BRONNENWERKPLEK','De juiste bron, binnen handbereik.','Vind richtlijnpassages en leg afspraken en informatie ernaast. Elke bron houdt zijn eigen context.', '<span class="badge warning">Prototype · beperkte voorbeeldset</span>')+
 '<div class="searchbox"><div class="search-title">Waar werk je aan?</div><div class="filters"><label>Vakgebied<select id="specialty">'+options(specialties,filters.specialty,'Alle vakgebieden')+'</select></label><label>Onderwerp<select id="topic">'+options(Object.fromEntries(Object.entries(topics).filter(([id])=>!filters.specialty||resources.some(r=>!r.demo&&r.specialties.includes(filters.specialty)&&r.topics.includes(id)))),filters.topic,'Alle onderwerpen')+'</select></label><label>Taak<select id="task">'+options(tasks,filters.task,'Alle taken')+'</select></label><label>Type bron<select id="layer">'+options(Object.fromEntries(Object.entries(layers).filter(([id])=>id!=='groningen')),filters.layer,'Alle typen')+'</select></label><button id="reset">Wis filters</button></div><div class="filter-foot"><span>Vaste bibliotheekfilters · geen patiëntkenmerken invullen</span><label class="toggle"><input type="checkbox" id="demo" '+(filters.demo?'checked':'')+'>Toon demonstratie van andere bronlagen</label></div></div>'+
 '<div class="notice">Startselectie voor vier vakgebieden; geen volledige dekking. Overzichten openen de officiële richtlijn. Gedeelde bronnen worden één keer getoond.</div><div class="stats"><span><strong>'+(new Set(actions.map(a=>a.source_id)).size+catalog.filter(c=>c.source_kind==='module').length)+'</strong>geselecteerde modules</span><span><strong>'+catalog.filter(c=>c.source_kind==='overview').length+'</strong>richtlijnoverzichten</span><span><strong>0</strong>professioneel goedgekeurd</span><span><strong>0</strong>gevalideerde lokale afspraken</span></div>'+
 (filters.demo?'<div class="notice">De paarse demonstratiekaarten laten zien hoe bronnen gecombineerd kunnen worden. Ze bevatten geen echte afspraken, patiëntinformatie of sociale verwijzingen.</div>':'')+
 '<div class="section-row"><h2>Bronnen voor jouw werk</h2><span class="count" role="status">'+found.length+' kaarten · '+found.filter(r=>!r.demo).length+' bronkaarten</span></div><div class="grid">'+(found.length?found.map(r=>card(r)).join(''):'<div class="empty"><h3>Voor deze selectie is nog geen inhoud beschikbaar.</h3><p>De startselectie dekt niet alle onderwerpen en taken. Wis eventueel een filter. Er worden geen antwoorden gegenereerd.</p>'+external('https://richtlijnendatabase.nl/','Zoek in de officiële Richtlijnendatabase')+'</div>')+'</div>';
}
function board(){
 const rows=resources.filter(r=>selected.has(r.id));
 if(integratedMode)return '<div class="ia-section-title"><div><p class="ia-eyebrow">MIJN WERKPLEK</p><h1>Mijn werkmap</h1></div><button id="clear-board">Maak leeg</button></div><p class="ia-caption">'+rows.length+' bewaarde kaarten · alleen in deze sessie. Richtlijnen en patiënteninformatie blijven afzonderlijke bronnen.</p><div class="actions ia-map-actions"><a href="#patienten">Patiënteninformatie toevoegen</a><button id="ia-package">Voorbeeld informatiepakket</button>'+(jgzMode?'<button id="save-package">Opslaan in Favorieten</button><a href="#favorieten">Mijn Favorieten</a>':'')+'</div><div class="compact-grid">'+(rows.length?rows.map(r=>card(r,true)).join(''):'<div class="empty">Bewaar kaarten via de knop Werkmap.</div>')+'</div>';
 return heading('MIJN CHIPBOARD','Verschillende bronnen. Eén werkplek.','Zet bronnen naast elkaar voor je eigen overzicht. Er wordt geen gezamenlijk medisch advies van gemaakt.','<button id="clear-board">Maak bord leeg</button>')+
 '<div class="notice">Dit bord bestaat alleen zolang deze pagina openstaat. Het bevat bronverwijzingen; geen dossiers, notities of patiëntgegevens.</div>'+
 '<div class="section-row"><h2>Naast elkaar</h2><span class="count">'+rows.length+' geselecteerde bronnen</span></div><div class="board-grid">'+(rows.length?rows.map(r=>card(r,true)).join(''):'<div class="empty"><h3>Maak je eerste bronnenoverzicht</h3><p>Kies in de bronnenwerkplek “+ Chipboard”. Zet eventueel de demonstratie van andere bronlagen aan.</p><a href="#bibliotheek">Naar de bronnenwerkplek</a></div>')+'</div>'+
 (rows.length>1?'<div class="panel"><h2>Verschillen zichtbaar houden</h2><p>Een lokale afspraak vervangt niet automatisch een landelijke bron. Bij tegenstrijdigheid blijven beide zichtbaar en is beoordeling door de inhoudelijk verantwoordelijke nodig.</p><div class="table-wrap"><table><thead><tr><th>Bron</th><th>Bereik</th><th>Beoordeling</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+esc(r.title)+'</td><td>'+esc(layers[r.layer])+'</td><td>'+(r.demo?'Geen echte inhoud':'Nog niet professioneel beoordeeld')+'</td></tr>').join('')+'</tbody></table></div></div>':'');
}
function modulePage(){return heading('MODULAIRE WERKPLEK','Aansluiten zonder alles te verbouwen.','Bronnen en applicaties krijgen een eigen modulekaart. Een vaste link opent de externe toepassing zonder patiënt- of zoekgegevens.')+
 '<div class="grid">'+modules.map(m=>'<article class="card"><span class="badge teal">'+(m.kind==='source-library'?'Actieve bronlaag':'Externe link')+'</span><h3>'+esc(m.name)+'</h3><p>'+(m.id==='pznl'?'61 bronkaarten uit Palliaweb en Overpalliatievezorg: richtlijnen, handreikingen, praktijkondersteuning en patiënteninformatie.':m.id==='groningen'?'Eerdere inventaris van 4.627 bronverwijzingen; inclusief contexten, toegangsstatus en bronrelaties.':m.kind==='source-library'?'Een vakgebied binnen dezelfde gedeelde catalogus. Gegevens staan los van de schermen en kunnen via een gecontroleerde release worden bijgewerkt.':'Opent het bestaande oncologieprototype. Geen gegevensuitwisseling of accountkoppeling geïmplementeerd.')+'</p><div class="card-bottom">'+(m.id==='pznl'?'<button data-pznl>Doorzoek PZNL-bronnen</button>':m.id==='groningen'?'<a href="#groningen">Open Groningse bronbibliotheek</a>':specialties[m.id]?'<button data-specialty="'+m.id+'">Open '+esc(m.name)+'</button>':external(m.url,'Open toepassing'))+'<div class="actions"><button data-manifest="'+m.id+'">Bekijk modulecontract</button></div></div></article>').join('')+
 '<article class="card local"><span class="badge">Aansluitbaar model</span><h3>Andere Inforium- en CHIP-modules</h3><p>Notes, regionale afspraken, patiëntenbibliotheken en externe toepassingen kunnen aansluiten via hetzelfde bron- en modulecontract. Deze koppelingen zijn nog niet gerealiseerd.</p><button id="contract">Bekijk aansluitroute</button></article></div>'+
 '<div class="panel"><h2>Van bron naar werkvloer</h2><div class="steps"><div class="step"><strong>01 · Bronadapter</strong>Leest toegestane bronmetadata</div><div class="step"><strong>02 · Bronregister</strong>Versie, eigenaar en herkomst</div><div class="step"><strong>03 · Redactie</strong>Controle op inhoud en bereik</div><div class="step"><strong>04 · Chipboard</strong>Vinden, combineren en openen</div></div><p>Deze versie gebruikt lokale JSON-bestanden. Een centrale catalogus-API, authenticatie voor redacteuren en automatische bronadapters zijn vervolgbouw.</p></div>';}
function management(){
 const statuses=['idle','detected','staged','reviewed','released'], pos=statuses.indexOf(update);
 return heading('BRONNEN & UPDATES','Actueel houden, met controle ertussen.','Publicatie, geldigheidsbeoordeling en raadpleging zijn afzonderlijke datums. Een nieuwe datum is geen nieuwe medische goedkeuring.')+
 '<div class="panel"><div class="section-row"><h2>Probeer een bronwijziging</h2><span class="badge demo">Simulatie · alleen in dit scherm</span></div><p>Doorloop de beheerroute met fictieve metadata. De echte bronrecords worden niet gewijzigd.</p><div class="steps">'+['Wijziging gevonden','Conceptversie','Redactie gecontroleerd','Versie vrijgegeven'].map((s,i)=>'<div class="step '+(pos>i?'done':'')+'"><strong>'+('0'+(i+1))+'</strong>'+s+'</div>').join('')+'</div><p id="update-status" role="status">'+[
  'Start een fictieve wijziging om de vervolgstappen te bekijken.',
  'Een fictieve nieuwe bronversie is gevonden. De huidige catalogus blijft beschikbaar.',
  'Conceptversie klaar. Vergelijking: versie 1 → versie 2; fictieve wijziging in contactgegevens. Inhoud, hergebruik en gekoppelde kaarten moeten worden gecontroleerd.',
  'Democontrole afgerond. In productie is een bevoegde redacteur met vastgelegde identiteit vereist.',
  'Demoversie vrijgegeven. In productie volgt een geteste release; eerdere versies blijven via Git beschikbaar.'
 ][pos]+'</p><div class="actions">'+(update==='idle'?'<button id="detect" class="primary">Simuleer bronwijziging</button>':update!=='released'?'<button id="advance" class="primary">'+({detected:'Maak democoncept',staged:'Simuleer redactionele controle',reviewed:'Geef demoversie vrij'}[update])+'</button>':'')+'<button id="reset-update">Herstart demonstratie</button></div></div>'+
 '<div class="panel"><h2>PZNL · Palliatieve zorg</h2><p>'+pznlRecords.length+' bronkaarten: richtlijnen en handreikingen, praktijkondersteuning en ingangen voor patiënten en naasten. Metadata geraadpleegd op 5 oktober 2026; geen volledige tekst geïmporteerd.</p><a href="#zoeken">Doorzoek PZNL via de bronselectie bovenaan</a></div><div class="panel"><h2>Bronregister</h2><p>'+sources.length+' bronverwijzingen, inclusief 3 algemene verwijzingen uit de overdracht. De catalogus bevat '+catalog.length+' aanvullende bronkaarten. Laatst opnieuw geraadpleegde modulemetadata: 4 oktober 2026.</p><div class="table-wrap"><table><thead><tr><th>Bron</th><th>Publicatie</th><th>Geldigheid beoordeeld</th><th>Raadpleging</th></tr></thead><tbody>'+sources.map(s=>'<tr><td>'+external(s.url,s.title)+'<small>Geen professionele goedkeuring van afgeleide records</small></td><td>'+date(s.published_at)+'</td><td>'+date(s.validity_assessed_at)+'</td><td>'+date(s.checked_at)+'</td></tr>').join('')+'</tbody></table></div></div><div class="panel"><h2>Als een bron verandert of niet opent</h2><p>Behoud de laatst gecontroleerde versie en datum. Zet hercontrole uit bij de eigenaar. Een technische fout bewijst niet dat medische informatie vervallen is. Het meegeleverde controlescript maakt een bereikbaarheidsrapport en wijzigt geen inhoud of goedkeuringsstatus.</p></div>';
}
function scope(){return heading('GEBRUIK & AFBAKENING','Een bronnenwerkplek voor professionals.','Dit prototype onderzoekt het vinden en combineren van kennis. Het is niet gereed voor klinische inzet.')+
 '<div class="two-columns"><section class="panel"><h2>Wat deze versie doet</h2><ul class="scope-list"><li>Bibliotheekmetadata filteren op onderwerp, taak en brontype.</li><li>Herleidbare bronkaarten naast elkaar tonen.</li><li>Vaste externe links openen zonder contextoverdracht.</li><li>Een modulaire structuur en beheerroute demonstreren.</li></ul></section><section class="panel"><h2>Grenzen van deze versie</h2><ul class="scope-list"><li>Alleen algemene zoektrefwoorden; geen patiëntgegevens, dossiers, uploads of vrije notities.</li><li>Geen diagnose, triage, dosering of gepersonaliseerde aanbeveling.</li><li>Geen taalmodel of gegenereerde medische antwoorden.</li><li>Geen professionele validatie van de drie voorbeeldrecords.</li></ul></section></div>'+
 '<div class="panel"><h2>MDR: ontwerpkeuze, geen vrijstelling</h2><p>Het ontbreken van patiëntgegevens of generatieve AI garandeert niet dat software buiten de MDR valt. Beoogd gebruik, functies en hun samenhang zijn bepalend. Ook zoeken kan een medisch doel dienen. Nieuwe functies en modulecombinaties vragen daarom een kwalificatiebeoordeling vóór klinische inzet.</p>'+external('https://health.ec.europa.eu/document/download/b45335c5-1679-4c71-a91c-fc7a4d37f12b_en?filename=md_mdcg_2019_11_guidance_qualification_classification_software_en.pdf','MDCG 2019-11 rev.1 · juni 2025')+'</div><div class="panel"><h2>Gegevens & herkomst</h2><p>Zoektrefwoorden, filters en bordselecties blijven alleen in paginageheugen. Zoekopdrachten worden niet in de URL gezet, opgeslagen of verstuurd. Er zijn geen analytics, cookies, externe lettertypen of AI-aanroepen toegevoegd. De hostingprovider ontvangt gewone webverzoeken; externe websites hanteren hun eigen privacybeleid.</p><p>Basis: Inforium_Richtlijnen_Codex_Overdracht.zip, versie 4 oktober 2026. De bronkaarten zijn beperkte redactionele voorbeelden. Daarnaast is de eerdere Groningse inventaris van 3 oktober 2026 gekoppeld. Geen volledige of opnieuw inhoudelijk gecontroleerde database of regionale afsprakenbank.</p></div>';
}

function groningenPage(){
 const rows=filterGroningen(groningenRecords,groningenFilters),pages=Math.max(1,Math.ceil(rows.length/12));groningenPageIndex=Math.min(groningenPageIndex,pages-1);
 const groups=Object.fromEntries([...new Set(groningenRecords.flatMap(r=>r.contexts.map(c=>c.group)))].filter(Boolean).sort((a,b)=>a.localeCompare(b,'nl')).map(v=>[v,v]));
 const paths=Object.fromEntries(groningenRecords.flatMap(r=>r.contexts).filter(c=>(!groningenFilters.group||c.group===groningenFilters.group)&&c.path).map(c=>[c.path,c.pathology]));
 return heading('BRONBIBLIOTHEEK · UMCG','Medische Oncologie Groningen','De eerdere inventaris, verbonden met je Chipboard. Landelijke richtlijnen en Groningse bronnen blijven afzonderlijk herkenbaar.')+
 '<div class="notice">Inventaris van 3 oktober 2026 · geen nieuwe inhoudelijke controle. Studie- en toegangsstatussen zijn momentopnamen. Controleer de actuele informatie altijd bij de bron.</div>'+
 '<div class="stats"><span><strong>'+groningenRecords.length.toLocaleString('nl-NL')+'</strong>verwijzingen</span><span><strong>'+groningenRecords.filter(r=>r.locked).length.toLocaleString('nl-NL')+'</strong>alleen metadata / inloggen</span><span><strong>'+groningenRecords.filter(r=>r.external).length+'</strong>externe verwijzingen</span></div>'+
 '<div class="searchbox"><div class="filters"><label>Voor wie<select id="g-audience">'+options({patient:'Patiënt',professional:'Professional',unknown:'Niet vastgesteld'},groningenFilters.audience,'Iedereen')+'</select></label><label>Soort informatie<select id="g-kind">'+options(groningenKinds,groningenFilters.kind,'Alle soorten')+'</select></label><label>Tumorgroep<select id="g-group">'+optionsSafe(groups,groningenFilters.group,'Alle groepen')+'</select></label><label>Tumortype<select id="g-path">'+optionsSafe(paths,groningenFilters.path,'Alle tumortypen')+'</select></label><button id="g-reset">Wis filters</button></div></div>'+
 '<div class="section-row"><h2>Groningse bronverwijzingen</h2><span class="count" role="status">'+rows.length+' resultaten · pagina '+(groningenPageIndex+1)+' van '+pages+'</span></div><div class="grid">'+(rows.length?rows.slice(groningenPageIndex*12,(groningenPageIndex+1)*12).map(r=>card(r)).join(''):'<div class="empty"><h3>Geen verwijzingen voor deze combinatie</h3><p>Wis een filter om andere bronnen te bekijken.</p></div>')+'</div><div class="actions"><button id="g-prev" '+(groningenPageIndex===0?'disabled':'')+'>Vorige pagina</button><button id="g-next" '+(groningenPageIndex+1>=pages?'disabled':'')+'>Volgende pagina</button></div>';
}
function optionsSafe(dict,current,all){return '<option value="">'+esc(all)+'</option>'+Object.entries(dict).sort((a,b)=>a[1].localeCompare(b[1],'nl')).map(([v,label])=>'<option value="'+esc(v)+'" '+(current===v?'selected':'')+'>'+esc(label)+'</option>').join('');}
function groningenDetails(r){
 const studyStatus={open:'Open in de inventaris',closed:'Gesloten in de inventaris',hold:'On hold in de inventaris',unknown:'Niet vermeld'};
 return '<div class="notice">UMCG-broninventaris van 3 oktober 2026; geen landelijke richtlijn en geen nieuwe professionele goedkeuring. '+(r.locked?'Alleen metadata beschikbaar; inloggen bij de bron kan nodig zijn.':'De actuele broninhoud en toegang zijn hier niet opnieuw vastgesteld.')+'</div>'+
 '<dl><dt>Categorie / doelgroep volgens inventaris</dt><dd>'+esc(groningenKinds[r.kind])+' / '+esc({patient:'Patiënt',professional:'Professional',unknown:'Onbekend'}[r.audience]||r.audience)+'</dd>'+
 (r.kind==='study'?'<dt>Studiestatus op inventarisdatum</dt><dd>'+esc(studyStatus[r.status]||r.status||'Onbekend')+' · controleer actuele status bij de bron</dd>':'')+
 '<dt>Broncode / bronversie</dt><dd>'+esc(r.code||'Niet vermeld')+' / '+esc(r.sourceVersion||'Niet vermeld')+'</dd><dt>Wijzigingsdatum uit eerdere inventaris</dt><dd>'+esc(r.modified||'Niet vermeld')+' · geen medische beoordelingsdatum</dd><dt>Bestemming</dt><dd>'+esc(new URL(r.url).hostname)+(r.external?' · externe website':'')+'</dd></dl>'+
 '<h3>Broncontexten uit eerdere inventaris</h3><p>De combinaties hieronder komen uit de inventaris; ze zijn geen patiëntselectie of behandeladvies.</p>'+ (r.contexts.length?'<div class="table-wrap"><table><thead><tr><th>Tumorgroep</th><th>Tumortype</th><th>Context</th><th>Status destijds</th></tr></thead><tbody>'+r.contexts.map(c=>'<tr><td>'+esc(c.group)+'</td><td>'+esc(c.pathology)+'</td><td>'+esc(c.phase||'Niet vermeld')+'</td><td>'+esc(c.status||'Niet vermeld')+'</td></tr>').join('')+'</tbody></table></div>':'<p>Geen specifieke context vastgelegd.</p>')+
 external(r.url,r.locked?'Open bron · mogelijk inloggen':'Open oorspronkelijke bron','source-link')+
 (r.related.length?'<h3>Gekoppelde bronnen in de inventaris</h3><p>Oorspronkelijke relaties; geen automatische aanbeveling.</p><div class="related">'+r.related.map(id=>{const other=groningenRecords.find(x=>x.id===id);return '<button data-related="'+id+'">'+esc(other.title)+'</button>';}).join('')+'</div>':'');
}


const refinement={extra:'',kind:'',audience:'',specialty:'',access:'',sort:'relevance'},usage=new Map();
let lastOpened=null;
const tumorSelection={group:'',pathology:'',phase:'',status:''};
let searchIndex=[],searchQuery='',searchPage=0,searchCollections=new Set(Object.keys(SOURCE_COLLECTIONS)),searchComplete=false;
function searchPageView(){
 const route=location.hash.slice(1),iaType=route==='patienten'?'patient':route==='nieuws'?'news':compactType;
 let currentIndex=integratedMode&&iaAge?searchIndex.filter(x=>x.record.inforium&&x.record.age===iaAge):searchIndex;
 if(oncologyMode&&Object.values(tumorSelection).some(Boolean)){const ids=new Set(filterTumorContexts(resources,tumorSelection).map(r=>r.id));currentIndex=currentIndex.filter(x=>ids.has(x.record.id));}
 if(compactMode){const result=compactSearch({index:currentIndex,query:searchQuery,collections:searchCollections,complete:searchComplete,refinement,usage,page:searchPage,type:integratedMode?iaType:compactType,filtersOpen:compactFiltersOpen,integrated:integratedMode,jgz:jgzMode,editionLabel:oncologyMode?'Oncologie':'JGZ'},{card,options,specialties});searchPage=result.page;compactHits=new Map(result.hits.map(h=>[h.record.id,h]));return (integratedMode?'<div class="ia-library-note">'+(oncologyMode?'Oncologie Groningen · herkomst en dekking bij Bronnenoverzicht.':jgzMode?'Afzonderlijke JGZ-werkplek · negen broncollecties; herkomst en dekking bij Bronnenoverzicht.':route==='nieuws'?'Nieuws uit de bestaande inventaris en duidelijk gemarkeerde voorbeelden; geen actuele nieuwsfeed.':'Echte bronverwijzingen en herkenbare Inforium-ontwerpvoorbeelden in één overzicht.')+(iaAge?' <strong>Leeftijdslabel voorbeelden: '+esc(iaAge)+'</strong> <button id="ia-age-clear">Wis leeftijd</button>':'')+'</div>':'')+(oncologyMode?tumorFilters(resources,tumorSelection):'')+result.html;}
 const response=searchResources(searchIndex,searchQuery,{collections:[...searchCollections],completeOnly:searchComplete});
 const refined=refineResults(searchIndex,response.results,refinement,usage),rows=refined.results;
 const kinds=Object.fromEntries([...new Set(searchIndex.map(x=>kindOf(x.record)))].sort((a,b)=>a.localeCompare(b,'nl')).map(k=>[k,k]));
 const pages=Math.max(1,Math.ceil(rows.length/12));searchPage=Math.min(searchPage,pages-1);
 const full=rows.filter(r=>r.matched===r.total).length;
 let resultHtml='',previous='';
 for(const hit of rows.slice(searchPage*12,(searchPage+1)*12)){
  const group=hit.matched===hit.total?'Alle trefwoorden gevonden':'Een deel van de trefwoorden gevonden';
  if(refinement.sort==='relevance'&&group!==previous){resultHtml+='<h2 class="search-group">'+group+'</h2>';previous=group;}
  resultHtml+=card(hit.record,false,hit);
 }
 return heading('ALGEMEEN ZOEKEN','Zoek over alle aangesloten bronnen.','Eén zoekopdracht in de geselecteerde richtlijn-, Groningse en PZNL-bronnen. Verfijn de resultaten met kenmerken en extra trefwoorden en kies de gewenste volgorde.')+
 '<p class="search-scope">'+searchIndex.length.toLocaleString('nl-NL')+' bronkaarten doorzoekbaar · titels, codes, onderwerpen, broncontexten en gekoppelde titels. Geen volledige documentteksten of live internetzoekactie.</p>'+
 '<div class="searchbox"><div class="filters search-filters"><label class="toggle"><input id="search-complete" type="checkbox" '+(searchComplete?'checked':'')+'>Alle trefwoorden moeten overeenkomen</label><button id="search-clear">Wis zoekopdracht</button></div><details class="ranking-help"><summary>Hoe wordt de volgorde bepaald?</summary><p>Eerst het aantal verschillende gevonden trefwoorden. Daarna de plek: broncode en titel tellen zwaarder dan broncontext of een gekoppelde titel. Een exacte titel of woordgroep krijgt extra gewicht. Woordbegin en enkele expliciet vermelde zoekverwanten tellen minder zwaar dan exacte woorden. Gelijke resultaten staan op titelvolgorde.</p><p>De volgorde drukt tekstovereenkomst uit, geen medische geschiktheid, kwaliteit of actualiteit. Bronstatussen blijven apart zichtbaar. Zoekverwanten zijn redactionele zoekhulpen, geen gelijkstelling van medische begrippen.</p></details></div>'+
 '<form id="refine-search" class="searchbox"><h2>Verfijn deze resultaten</h2><label for="refine-extra">Aanvullende trefwoorden — allemaal vereist binnen de huidige resultaten</label><div class="global-search-row"><input id="refine-extra" type="search" maxlength="200" autocomplete="off" spellcheck="false" value="'+esc(refinement.extra)+'" placeholder="Bijvoorbeeld pijn of naasten"><button type="submit">Verfijnen</button></div><div class="refine-filters">'+
 '<label>Soort informatie<select id="refine-kind">'+options(kinds,refinement.kind,'Alle soorten')+'</select></label>'+
 '<label>Doelgroep<select id="refine-audience">'+options({professional:'Zorgprofessionals',patient:'Patiënten en naasten',unknown:'Niet vastgelegd'},refinement.audience,'Alle doelgroepen')+'</select></label>'+
 '<label>Vakgebied volgens catalogus<select id="refine-specialty">'+options({...specialties,unknown:'Niet ingedeeld'},refinement.specialty,'Alle vakgebieden')+'</select></label>'+
 '<label>Toegang volgens inventaris<select id="refine-access">'+options({locked:'Mogelijk inloggen',unflagged:'Niet als afgeschermd gemarkeerd',unknown:'Niet vastgelegd'},refinement.access,'Alle toegangsstatussen')+'</select></label>'+
 '<label>Volgorde<select id="refine-sort">'+options({relevance:'Grootste overeenkomst',used:'Meest gebruikt · deze sessie',source:'Broncollectie, daarna alfabet',alphabet:'Alfabet · A–Z'},refinement.sort,'Kies volgorde').replace('<option value="">Kies volgorde</option>','')+'</select></label></div><p class="muted">Filters combineren met EN. Niet-ingedeelde bronnen vallen buiten een specifiek vakgebied. Gebruik alleen algemene trefwoorden, geen patiëntgegevens.</p><p id="usage-explanation">Meest gebruikt telt geopende bronkaarten in deze browsersessie. Geen landelijke populariteit; geen opslag of verzending. Gelijke aantallen worden op overeenkomst gesorteerd.</p><button type="button" id="refine-reset">Wis verfijning en herstel volgorde</button></form>'+
 (!searchCollections.size?'<div class="empty"><h2>Selecteer ten minste één broncollectie</h2><p>Vink bovenaan de bronnen aan die je wilt doorzoeken.</p></div>':(response.error||refined.error)?'<div class="notice" role="alert">'+esc(response.error||refined.error)+'</div>':!response.terms.length?'<div class="empty"><h2>Vul bovenaan enkele trefwoorden in</h2><p>Bijvoorbeeld “borstkanker radiotherapie”, “neus anamnese” of een broncode. Gebruik algemene trefwoorden, geen patiëntgegevens.</p></div>':
 '<div class="section-row"><h2>Resultaten voor “'+esc(searchQuery)+'”</h2><span class="count" role="status">'+rows.length+' resultaten (van '+response.results.length+' vóór verfijning) · '+full+' met alle trefwoorden · pagina '+(searchPage+1)+' van '+pages+'</span></div>'+
 (rows.length?'<div class="grid">'+resultHtml+'</div><div class="actions"><button id="search-prev" '+(searchPage===0?'disabled':'')+'>Vorige pagina</button><button id="search-next" '+(searchPage+1>=pages?'disabled':'')+'>Volgende pagina</button></div>':'<div class="empty"><h3>Geen trefwoordovereenkomst gevonden</h3><p>Probeer minder of andere woorden, wis de verfijning of kies alle broncollecties. De catalogus bevat niet alle medische informatie. Er wordt geen antwoord gegenereerd.</p></div>'));
}
function searchReason(hit){
 return '<section class="match search-reasons" aria-label="Waarom gevonden"><p><b>Waarom gevonden</b></p><strong>'+hit.matched+' van '+hit.total+' trefwoorden gevonden</strong>'+
 (hit.phraseBonus?'<p>Exacte woordgroep in de titel telt extra mee.</p>':'')+
 '<ul>'+hit.matches.map(m=>'<li><b>'+esc(m.term)+'</b> · '+esc(m.field)+(m.mode==='alias'?' · zoekverwant: '+esc(m.alias):m.mode==='prefix'?' · woordbegin':'')+'<span>“'+esc(m.snippet)+'”</span></li>').join('')+'</ul>'+
 (hit.refinementMatches?.length?'<p><b>Aanvullende trefwoorden gevonden</b></p><ul>'+hit.refinementMatches.map(m=>'<li>'+esc(m.term)+' · '+esc(m.field)+(m.mode==='alias'?' · zoekverwant: '+esc(m.alias):m.mode==='prefix'?' · woordbegin':'')+'<span>“'+esc(m.snippet)+'”</span></li>').join('')+'</ul>':'')+
 (refinement.sort==='used'?'<p>Deze sessie: '+hit.uses+' keer bronkaart geopend.</p>':'')+
 (hit.missing.length?'<p>Niet gevonden: '+hit.missing.map(esc).join(', ')+'</p>':'')+'</section>';
}
document.addEventListener('submit',e=>{
 if(e.target.id==='refine-search'){e.preventDefault();refinement.extra=$('#refine-extra').value.trim();searchPage=0;render();$('#refine-extra').focus();return;}
 if(e.target.id!=='global-search')return;
 e.preventDefault();searchQuery=$('#global-query').value.trim();searchPage=0;
 location.hash='zoeken';render();$('#main').focus();
});

function render(){
 if(compactMode&&document.querySelector('#compact-filters'))compactFiltersOpen=document.querySelector('#compact-filters').open;
 const page=location.hash.slice(1)||(integratedMode?'start':compactMode?'zoeken':'bibliotheek');
 $('#source-collections').innerHTML='<legend>Welke bronnen wil je doorzoeken?</legend><div class="source-options">'+Object.entries(SOURCE_COLLECTIONS).map(([id,label])=>'<label><input type="checkbox" data-collection="'+id+'" '+(searchCollections.has(id)?'checked':'')+'> <span>'+esc(label)+' <small>('+searchIndex.filter(x=>collectionOf(x.record)===id).length+')</small></span></label>').join('')+'</div><div class="actions"><button type="button" id="sources-all">Alle bronnen</button><button type="button" id="sources-none">Geen bronnen</button></div>';
 const views={...(integratedMode?{start:()=>integratedHome(resources,selected),patienten:searchPageView,nieuws:searchPageView}:{}),zoeken:searchPageView,bibliotheek:library,groningen:groningenPage,board,modules:modulePage,beheer:management,kaders:scope};
 const jgzViews={start:()=>oncologyMode?oncologyHome(resources,selected):jgzHome(resources,selected),zoeken:searchPageView,patienten:searchPageView,board,favorieten:favoritesPage,nieuws:oncologyMode?searchPageView:jgzNews,bronnen:()=>oncologyMode?oncologyRegister(resources):jgzRegister(resources),kaders:scope};
 $('#main').innerHTML=jgzMode?(jgzViews[page]||jgzViews.start)():(views[page]||library)();
 document.querySelectorAll('[data-nav]').forEach(a=>{const active=a.dataset.nav===page; a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
 $('#board-count').textContent=selected.size;
 if(compactMode){
  $('#compact-sources-label').textContent='Bronnen · '+searchCollections.size+' van '+Object.keys(SOURCE_COLLECTIONS).length+' geselecteerd';
  decorateCompact();
  if(page!=='zoeken'){const nodes=[...document.querySelectorAll('#main > .notice, #main > .stats, #main > .heading .intro')];if(nodes.length){const details=document.createElement('details');details.className='compact-page-info';details.innerHTML='<summary>Toelichting en bronstatus</summary>';nodes.forEach(n=>details.append(n));$('#main .heading')?.after(details);}}
 }
}
function showDialog(html){$('#detail-body').innerHTML=html;$('#detail').showModal();}
function showResource(id){
 const r=resources.find(r=>r.id===id); if(!r)return;
 if(!r.demo){usage.set(id,(usage.get(id)||0)+1);lastOpened=id;}
 let html='<div class="dialog-top"><span class="badge '+(r.demo?'demo':'warning')+'">'+(r.demo?'Demonstratie':'Redactioneel te beoordelen')+'</span><button class="close" data-close>Sluiten ✕</button></div><h2 id="detail-title">'+esc(r.title)+'</h2><p>'+esc(r.description)+'</p>';
 if(r.inforium){html+=inforiumDetails(r);}
 else if(r.radiotherapy){html+='<dl><dt>Broncollectie</dt><dd>'+esc(SOURCE_COLLECTIONS[r.collection])+'</dd><dt>Type</dt><dd>'+esc(r.kind)+'</dd><dt>Titel / linkvermelding geraadpleegd</dt><dd>'+date(r.checked_at)+'</dd><dt>Herkomst</dt><dd>'+external(r.provenance_url,'Pagina waarop de bron is gevonden')+'</dd><dt>Inhoudelijk beoordeeld</dt><dd>Niet vastgesteld</dd></dl>'+(r.collection==='rt-study'?'<div class="notice">Studie-inclusiestatus niet vastgesteld. Een vermelding betekent niet dat een studie nog open is of geschikt is voor een patiënt. Controleer dit bij de onderzoeksgroep.</div>':'')+external(r.url,'Open oorspronkelijke bron','source-link');}
 else if(r.patientImport){html+=(r.link_review?'<div class="notice">'+esc(r.link_review)+'. Deze kaart wordt niet opgenomen in een patiënteninformatiepakket.</div>':'')+'<dl><dt>Broncollectie</dt><dd>'+esc(r.owner)+'</dd><dt>Herkomstbestand</dt><dd>'+esc(r.source_file)+'</dd><dt>Exportdatum</dt><dd>'+date(r.export_date)+' · geen publicatie- of controledatum</dd><dt>Invoerdatum</dt><dd>'+date(r.imported_at)+'</dd><dt>Taal volgens import</dt><dd>'+(r.languages?.map(l=>esc(LANGUAGE_LABELS[l]||l)).join(', ')||'Niet vastgelegd')+'</dd><dt>Bereikbaarheid en inhoudelijke actualiteit</dt><dd>Niet opnieuw vastgesteld</dd><dt>Samengevoegde exportvermeldingen</dt><dd>'+r.variants.map(v=>esc(v.file||r.source_file)+' · rij '+esc(v.row)+' · '+esc(v.title)).join('<br>')+'</dd><dt>Zoektrefwoorden uit export</dt><dd>'+r.keywords.map(esc).join(', ')+'</dd></dl>'+(r.metadata_note?'<p>'+esc(r.metadata_note)+'</p>':'')+(r.link_checked_at?'<p>Technische linkcontrole: '+date(r.link_checked_at)+'; geen inhoudelijke beoordeling.</p>':'')+(r.title_correction?'<p>'+esc(r.title_correction)+'</p>':'')+(r.variants?.some(v=>v.source_page)?'<p>Bronpagina bij video: '+[...new Set(r.variants.map(v=>v.source_page).filter(Boolean))].map(u=>external(u,'NVOG / deGynaecoloog.nl')).join(' · ')+'</p>':'')+ (r.url?external(r.url,'Open oorspronkelijke bron','source-link'):'<p>Oorspronkelijke linkwaarde: '+esc(r.original_url||'Ontbreekt')+'</p>');}
 else if(r.pznl||r.primaryGuideline){html+='<dl><dt>Broncollectie</dt><dd>'+esc(SOURCE_COLLECTIONS[r.collection])+'</dd><dt>Type</dt><dd>'+esc(r.kind)+'</dd><dt>Titel en link geraadpleegd</dt><dd>'+date(r.checked_at)+'</dd><dt>Laatst gewijzigd volgens het bronoverzicht</dt><dd>'+date(r.index_updated_at)+'</dd><dt>Geldigheid inhoudelijk beoordeeld</dt><dd>Niet vastgesteld; overzichtsdatum is geen geldigheidsbeoordeling.</dd><dt>Herkomst</dt><dd>'+external(r.provenance_url,'Bron van deze metadata')+'</dd><dt>Hergebruik</dt><dd>'+esc(r.rights)+'</dd></dl><p>Alleen bronnavigatie. Geen volledige tekst of automatisch behandeladvies. Raadpleeg de bron voor de actuele versie en herzieningsstatus.</p>'+external(r.url,'Open oorspronkelijke bron','source-link');}
 else if(r.groningen){html+=groningenDetails(r);}
 else if(r.navigation){html+='<div class="notice">Alleen bronnavigatie. Geen samenvatting, behandeladvies of professionele inhoudelijke goedkeuring.</div><dl><dt>Type pagina</dt><dd>'+esc(r.source_kind==='overview'?'Richtlijnoverzicht; onderliggende modules niet automatisch opgenomen':'Afzonderlijke richtlijnmodule')+'</dd><dt>Vindbaar vanuit</dt><dd>'+r.specialties.map(k=>esc(specialties[k])).join(', ')+'</dd><dt>Publicatie</dt><dd>'+date(r.published_at)+'</dd><dt>Geldigheid beoordeeld volgens de bron</dt><dd>'+date(r.validity_assessed_at)+'</dd><dt>Titel, URL en metadata geraadpleegd</dt><dd>'+date(r.checked_at)+'</dd><dt>Catalogusversie</dt><dd>'+esc(r.version)+'</dd><dt>Hergebruik</dt><dd>'+esc(r.rights)+'</dd></dl>'+external(r.url,'Open oorspronkelijke bron','source-link');}
 else if(r.demo) html+='<div class="notice">Geen echte afspraak of patiënteninformatie. Dit is een invulmodel voor een toekomstige bronkoppeling.</div><dl><dt>Type</dt><dd>'+esc(layers[r.layer])+'</dd><dt>Benodigde brongegevens</dt><dd>Eigenaar, regio, doelgroep, originele URL, versie, geldigheidsperiode, hergebruikrechten en redactionele controle.</dd><dt>Relatie tot landelijke bronnen</dt><dd>Aanvulling, afwijking of procesafspraak expliciet vastleggen; nooit stilzwijgend samenvoegen.</dd></dl>';
 else {
 const a=r.record,s=r.source;
 const labels={suspected_condition:'Toepassingsgebied: mogelijke luchtwegallergie',setting:'Setting: tweede / derde lijn',age_group:'Doelgroep: kinderen'};
 html+='<div class="notice">'+(a.record_type==='navigation_only'?'Uitsluitend bronnavigatie; geen zelfstandige diagnostische beslisregel.':'Deze kaart beschrijft een bronpassage, niet wat bij een individuele patiënt moet gebeuren.')+'</div><dl><dt>Inforium Notes · toepassingsgebied van de bron</dt><dd>'+(a.applicability.any_of.map(g=>g.all_of.map(c=>esc(labels[c.field]||c.field)).join(' én ')).filter(Boolean).join(' OF ') || 'Niet als zelfstandig criterium gemodelleerd')+'</dd><dt>Uitsluitingen</dt><dd>Niet volledig geïnventariseerd. Geen claim van volledige toepasbaarheid.</dd><dt>Bronsectie</dt><dd>'+esc(a.source_section)+'</dd><dt>Officiële aanbeveling</dt><dd>Lees in de oorspronkelijke module; niet volledig overgenomen.</dd><dt>Onderbouwing en overwegingen</dt><dd>Afzonderlijke secties in de bron. Lees samen met de aanbeveling.</dd><dt>Aanbevelingsmodaliteit in overdracht</dt><dd>'+esc({do:'Doen · beperkte redactionele interpretatie',not_applicable:'Niet van toepassing'}[a.modality]||a.modality)+'</dd><dt>Bewijszekerheid</dt><dd>Niet vastgelegd in het actierecord; geen GRADE-niveau toegekend.</dd><dt>Redactionele notitie</dt><dd>'+esc(a.review_note)+'</dd><dt>Publicatie / geldigheid beoordeeld</dt><dd>'+date(s.published_at)+' / '+date(s.validity_assessed_at)+'</dd><dt>Raadpleging in overdracht</dt><dd>'+date(s.checked_at)+'</dd></dl>'+external(s.url,'Open oorspronkelijke module','source-link')+'<p class="muted">Opent de bron niet? De status is dan onbekend; behoud de laatste controledatum en laat de bron opnieuw controleren.</p>';
 }
 showDialog(html+patientActions(r)+(jgzMode?'<button data-favorite="'+esc(r.id)+'">'+(favorites.cards.includes(r.id)?'★ In Favorieten':'☆ Opslaan in Favorieten')+'</button>':''));
 if(compactMode){const url=sourceUrl(r);$('#detail-body').querySelectorAll('a.source-link').forEach(a=>a.remove());if(url)$('#detail-body .dialog-top').insertAdjacentHTML('afterend',external(url,'Open oorspronkelijke bron','source-link compact-source-top'));decorateCompact();const hit=compactHits.get(id);if(hit&&(hit.total||hit.refinementMatches?.length)&&location.hash==='#zoeken')$('#detail-body').insertAdjacentHTML('beforeend',searchReason(hit));}
}
document.addEventListener('click',async event=>{
 if(oncologyMode&&event.target.closest('a[href="#nieuws"]')){searchCollections=new Set(['groningen']);searchQuery='';$('#global-query').value='';Object.assign(refinement,{extra:'',kind:'',audience:'',specialty:'',access:'',sort:'relevance'});searchPage=0;}

 if(compactMode){const row=event.target.closest('[data-detail-card]');if(row&&!event.target.closest('a,button,input,select,summary')){showResource(row.dataset.detailCard);return;}}
 const button=event.target.closest('button');if(!button)return;
 if(jgzMode&&button.dataset.favorite){const id=button.dataset.favorite;if(!resources.some(r=>r.id===id))return;const cards=favorites.cards.includes(id)?favorites.cards.filter(x=>x!==id):[...favorites.cards,id];if(saveFavorites({...favorites,cards})){button.textContent=cards.includes(id)?'★ In Favorieten':'☆ Opslaan in Favorieten';render();toast('Favorieten bijgewerkt');}return;}
 if(jgzMode&&button.id==='save-package'){if(!selected.size){toast('Voeg eerst bronnen toe aan je werkmap');return;}showDialog('<div class="dialog-top"><button data-close>Annuleren</button></div><h2 id="detail-title">Werkpakket opslaan</h2><form id="package-name-form"><label for="package-name">Naam van het werkpakket</label><input id="package-name" name="package-name" required maxlength="80" autocomplete="off" aria-describedby="package-name-help" placeholder="Bijvoorbeeld: Voeding en groei"><p id="package-name-help">Gebruik een algemene onderwerpnaam, zonder patiëntgegevens. Opgeslagen in deze browser.</p><button type="submit" class="primary">Opslaan in Favorieten</button></form>');$('#package-name').focus();return;}

 if(jgzMode&&button.dataset.restorePackage){const p=favorites.packages.find(p=>p.id===button.dataset.restorePackage);if(p){p.cards.filter(id=>resources.some(r=>r.id===id)).forEach(id=>selected.add(id));location.hash='board';render();toast('Werkpakket toegevoegd aan je werkmap');}return;}
 if(jgzMode&&button.dataset.removePackage){if(saveFavorites({...favorites,packages:favorites.packages.filter(p=>p.id!==button.dataset.removePackage)}))render();return;}
 if(button.dataset.patientAction){
  const r=resources.find(r=>r.id===button.dataset.resource),url=patientLink(r);if(!url)return;
  if(button.dataset.patientAction==='copy'){
   try{await navigator.clipboard.writeText(url);toast('Link gekopieerd');}
   catch{showDialog(sharingDialog(r,'copy'));$('#patient-share-link').focus();$('#patient-share-link').select();}
  }else{showDialog(sharingDialog(r,button.dataset.patientAction));}
  return;
 }
 if(button.hasAttribute('data-content-type')){if(integratedMode){iaAge='';location.hash='zoeken';}compactType=button.dataset.contentType;searchPage=0;render();$('[data-content-type="'+compactType+'"]').focus();}
 if(integratedMode&&button.hasAttribute('data-ia-examples')){iaAge='';searchQuery='';$('#global-query').value='';compactType=button.dataset.iaExamples;searchCollections=new Set(['inforium']);searchPage=0;location.hash='zoeken';render();}
 if(integratedMode&&button.hasAttribute('data-ia-age')){iaAge=button.dataset.iaAge;searchQuery='';$('#global-query').value='';compactType='patient';searchCollections=new Set(['inforium']);searchPage=0;location.hash='zoeken';render();}
 if(button.id==='ia-age-clear'){iaAge='';render();}
 if(integratedMode&&button.hasAttribute('data-ia-knowledge')){iaAge='';searchQuery='';$('#global-query').value='';compactType='knowledge';searchCollections=new Set(Object.keys(SOURCE_COLLECTIONS));searchPage=0;location.hash='zoeken';render();}
 if(button.dataset.oncoCollection&&oncologyMode){iaAge='';compactType='';searchQuery='';$('#global-query').value='';searchCollections=new Set([button.dataset.oncoCollection]);Object.assign(refinement,{extra:'',kind:'',audience:'',specialty:'',access:'',sort:'relevance'});searchPage=0;location.hash='zoeken';render();return;}
 if(button.dataset.jgzCollection&&jgzMode){iaAge='';compactType=JGZ_KNOWLEDGE.includes(button.dataset.jgzCollection)?'knowledge':'patient';searchQuery='';$('#global-query').value='';searchCollections=new Set([button.dataset.jgzCollection]);Object.assign(refinement,{extra:'',kind:'',audience:'',specialty:'',access:'',sort:'relevance'});searchPage=0;location.hash='zoeken';render();}
 if(button.dataset.patientCollection){iaAge='';compactType='patient';searchQuery='';$('#global-query').value='';searchCollections=new Set([button.dataset.patientCollection]);Object.assign(refinement,{extra:'',kind:'',audience:'',specialty:'',access:'',sort:'relevance'});searchPage=0;location.hash='zoeken';render();}
 if(button.id==='ia-package'&&integratedMode)showDialog(packagePreview(resources,selected));
 if(button.hasAttribute('data-pznl')){searchCollections=new Set(['palliaweb','pznl-patient']);searchQuery='palliatieve zorg';$('#global-query').value=searchQuery;searchPage=0;location.hash='zoeken';render();}
 if(button.id==='sources-all'||button.id==='sources-none'){searchCollections=button.id==='sources-all'?new Set(Object.keys(SOURCE_COLLECTIONS)):new Set();searchPage=0;render();$('#'+button.id).focus();}
 if(button.id==='tumor-reset'){Object.keys(tumorSelection).forEach(k=>tumorSelection[k]='');searchPage=0;render();return;}
 if(button.id==='refine-reset'){Object.keys(tumorSelection).forEach(k=>tumorSelection[k]='');iaAge='';if(compactMode){compactType='';searchComplete=false;}Object.assign(refinement,{extra:'',kind:'',audience:'',specialty:'',access:'',sort:'relevance'});searchPage=0;render();$('#refine-extra').focus();}
 if(button.id==='search-clear'){searchQuery='';$('#global-query').value='';searchPage=0;render();$('#global-query').focus();}
 if(button.id==='search-prev'||button.id==='search-next'){searchPage+=button.id==='search-next'?1:-1;render();$('#main').focus();}
 if(button.dataset.related){$('#detail').close();showResource(button.dataset.related);}
 if(button.id==='g-reset'){Object.assign(groningenFilters,{audience:'',kind:'',group:'',path:''});groningenPageIndex=0;render();$('#g-audience').focus();}
 if(button.id==='g-prev'||button.id==='g-next'){groningenPageIndex+=button.id==='g-next'?1:-1;render();$('#'+button.id).focus();}
 if(button.hasAttribute('data-close')) $('#detail').close();
 if(button.dataset.open)showResource(button.dataset.open);
 if(button.dataset.pin){const id=button.dataset.pin;selected.has(id)?selected.delete(id):selected.add(id);render();document.querySelector('[data-pin="'+id+'"]')?.focus();toast((selected.has(id)?'Bron toegevoegd aan je ':'Bron verwijderd van je ')+(integratedMode?'werkmap':'Chipboard'));}
 if(button.dataset.specialty){Object.assign(filters,{specialty:button.dataset.specialty,topic:'',task:'',layer:''});location.hash='bibliotheek';render();$('#specialty').focus();}
 if(button.id==='reset'){Object.assign(filters,{specialty:'',topic:'',task:'',layer:'',demo:false});render();$('#topic').focus();}
 if(button.id==='clear-board'){selected.clear();render();$('#clear-board').focus();toast(integratedMode?'Werkmap leeggemaakt':'Chipboard leeggemaakt');}
 if(['detect','advance','reset-update'].includes(button.id)){update=stageUpdate(update,button.id==='detect'?'detect':button.id==='advance'?'advance':'reset');render();($('#advance')||$('#reset-update')).focus();}
 if(button.dataset.manifest){const m=modules.find(m=>m.id===button.dataset.manifest);showDialog('<div class="dialog-top"><span class="badge">Modulecontract v1</span><button data-close>Sluiten ✕</button></div><h2 id="detail-title">'+esc(m.name)+'</h2><p>Dit manifest beschrijft alleen de module, de vaste bestemming en toegestane functies.</p><pre>'+esc(JSON.stringify(m,null,2))+'</pre>');}
 if(button.id==='contract')showDialog('<div class="dialog-top"><span class="badge">Aansluitroute</span><button data-close>Sluiten ✕</button></div><h2 id="detail-title">Een module toevoegen</h2><ol class="scope-list"><li>Leg eigenaar, bronrechten en beoogd gebruik vast.</li><li>Voeg een manifest toe aan data/modules.json met vaste HTTPS-link en patientData: false.</li><li>Map bronmetadata naar een eigen adapter; behoud versie en herkomst.</li><li>Laat inhoud en modulecombinatie beoordelen.</li><li>Valideer, test en publiceer een nieuwe versie via GitHub.</li></ol><p>Een link is nog geen API-integratie. Uitwisseling en authenticatie vereisen aanvullende bouw en toetsing.</p>');
});
document.addEventListener('change',e=>{
 if(oncologyMode&&e.target.dataset.tumorFilter){const key=e.target.dataset.tumorFilter;tumorSelection[key]=e.target.value;if(key==='group'){tumorSelection.pathology='';tumorSelection.phase='';tumorSelection.status='';}searchCollections.add('groningen');searchPage=0;render();document.querySelector('[data-tumor-filter="'+key+'"]').focus();return;}
 if(e.target.id.startsWith('refine-')){const key=e.target.id.slice(7);if(key!=='extra'&&Object.hasOwn(refinement,key)){refinement.extra=$('#refine-extra').value.trim();refinement[key]=e.target.value;searchPage=0;render();$('#refine-'+key).focus();}}
 if(e.target.dataset.collection){const id=e.target.dataset.collection;if(e.target.checked)searchCollections.add(id);else searchCollections.delete(id);searchPage=0;render();$('[data-collection="'+id+'"]').focus();}
 if(e.target.id==='search-complete'){searchComplete=e.target.checked;searchPage=0;render();$('#search-complete').focus();}
 if(e.target.id.startsWith('g-')){const key=e.target.id.slice(2);if(Object.hasOwn(groningenFilters,key)){groningenFilters[key]=e.target.value;if(key==='group')groningenFilters.path='';groningenPageIndex=0;render();$('#g-'+key).focus();}}
 if(e.target.id==='specialty'){Object.assign(filters,{specialty:e.target.value,topic:'',task:''});render();$('#specialty').focus();}
 if(['topic','task','layer'].includes(e.target.id)){const id=e.target.id;filters[id]=e.target.value;render();$('#'+id).focus();}
 if(e.target.id==='demo'){filters.demo=e.target.checked;render();$('#demo').focus();}
});
$('#detail').addEventListener('close',()=>{if(location.hash==='#zoeken'&&lastOpened){const id=lastOpened;lastOpened=null;render();$('[data-open="'+id+'"]')?.focus();}});
document.addEventListener('toggle',e=>{if(e.target.id==='compact-filters'&&e.target.isConnected)compactFiltersOpen=e.target.open;},true);
window.addEventListener('hashchange',()=>{render();$('#main').focus();});
try {
 if(jgzMode){resources=oncologyMode?validateOncology(await read('./data/oncology-library.json')):validateJgzLibrary(await read('./data/jgz-library.json'));groningenRecords=resources.filter(r=>r.groningen);searchIndex=buildSearchIndex(resources,{topics,specialties,tasks,kinds:groningenKinds});render();}else{
 [sources,actions,modules,catalog,groningenPayload,pznlPayload]=await Promise.all([read('./data/bronnen.json'),read('./data/voorbeeldacties.json'),read('./data/modules.json'),read('./data/catalogus.json'),read('./data/groningen.json'),read('./data/pznl.json')]);
 sources=[...sources,...catalog];
 modules.forEach(validateManifest); groningenRecords=decodeGroningen(groningenPayload); pznlRecords=decodePznl(pznlPayload); resources=[...makeResources(),...groningenRecords,...pznlRecords,...decodePrimaryGuidelines(await read('./data/primary-guidelines.json')),...mergeSourceImports(decodePatientSources(await read('./data/patient-sources.json')),decodeExtraSources(await read('./data/extra-sources.json')))];if(integratedMode){inforiumRecords=decodeInforium(await read('./data/inforium-examples.json'));resources.push(...inforiumRecords);}searchIndex=buildSearchIndex(resources.filter(r=>!r.demo||r.inforium),{topics,specialties,tasks,kinds:groningenKinds},{includeDemos:integratedMode});render();
}
} catch(error){$('#main').innerHTML='<div class="empty"><h1>De brongegevens konden niet worden geladen.</h1><p>Er worden geen vervangende antwoorden getoond. Probeer de pagina opnieuw te laden.</p><a href="./">Opnieuw laden</a></div>';console.error(error);}

document.addEventListener('submit',event=>{
 if(!jgzMode||event.target.id!=='package-name-form')return;
 event.preventDefault();const input=$('#package-name'),name=input.value.trim();
 if(!name){input.setCustomValidity('Vul een naam in.');input.reportValidity();return;}
 const cards=[...selected].sort();
 if(saveFavorites({...favorites,packages:[...favorites.packages,{id:crypto.randomUUID(),name:name.slice(0,80),cards}]})){$('#detail').close();toast('Werkpakket opgeslagen: '+name);}
});
document.addEventListener('input',event=>{if(event.target.id==='package-name')event.target.setCustomValidity('');});
