import {icon} from './icons.js';
import {searchResources,SOURCE_COLLECTIONS,collectionOf} from './search.js';
import {refineResults,kindOf,audienceOf} from './refine.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// Future adapters may supply contentType; existing collections retain their identity.
export function contentTypeOf(r){
 if(['knowledge','patient','news'].includes(r.contentType))return r.contentType;
 return r.kind==='news'?'news':audienceOf(r)==='patient'?'patient':'knowledge';
}
export const sourceUrl=r=>r.demo?null:r.url||r.source?.url||null;
export function compactCard(r,selected,hit,{boardLabel='Chipboard'}={}){
 const url=sourceUrl(r),status=r.link_review?'Link controleren':r.patientImport?'Export 05-10-2026':r.demo?'Demonstratie':r.locked?'Mogelijk inloggen':r.groningen?'Inventaris 03-10-2026':'Bronverwijzing';
 return '<article class="compact-card" data-detail-card="'+esc(r.id)+'"><h3><span class="content-icon content-icon-'+contentTypeOf(r)+'">'+icon(contentTypeOf(r))+'</span>'+(url?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer" title="'+esc(r.title)+' — open oorspronkelijke bron">'+esc(r.title)+' '+icon('external')+'</a>':esc(r.title))+'</h3><div class="compact-meta">'+esc(SOURCE_COLLECTIONS[collectionOf(r)]||r.owner)+' · '+esc(kindOf(r))+'</div><div class="compact-card-bottom"><span class="compact-status">'+(r.locked?icon('lock'):'')+esc(status)+(hit?.total?' · '+hit.matched+'/'+hit.total+' trefwoorden':'')+'</span><div class="actions"><button data-open="'+esc(r.id)+'" aria-label="Details: '+esc(r.title)+'">'+icon('info')+'Details</button><button data-pin="'+esc(r.id)+'" class="'+(selected.has(r.id)?'saved':'')+'" aria-label="'+(selected.has(r.id)?'Verwijder van':'Voeg toe aan')+' '+esc(boardLabel)+': '+esc(r.title)+'">'+(selected.has(r.id)?icon('check')+'Bewaard':icon('bookmark')+esc(boardLabel))+'</button></div></div></article>';
}
export function compactSearch(state,{card,options,specialties}){
 const {index,query,collections,complete,refinement,usage,type}=state;
 const response=query.trim()?searchResources(index,query,{collections:[...collections],completeOnly:complete}):{terms:[],error:'',results:index.filter(x=>collections.has(collectionOf(x.record))).map(x=>({record:x.record,matches:[],missing:[],matched:0,total:0,score:0,phraseBonus:0}))};
 const refined=refineResults(index,response.results,refinement,usage);
 const rows=refined.results.filter(h=>!type||contentTypeOf(h.record)===type);
 const pages=Math.max(1,Math.ceil(rows.length/12)),page=Math.min(state.page,pages-1);
 const active=[refinement.kind,refinement.audience,refinement.specialty,refinement.access,complete].filter(Boolean).length;
 const kinds=Object.fromEntries([...new Set(index.map(x=>kindOf(x.record)))].sort((a,b)=>a.localeCompare(b,'nl')).map(k=>[k,k]));
 const tabs={'':'Alles',knowledge:'Kennisbronnen',patient:'Patiënteninformatie',news:'Nieuws'};
 const html='<div class="compact-heading"><div><h1>'+(state.integrated?(type==='patient'?'Patiënteninformatie':type==='news'?'Nieuws & inspiratie':'Alle informatie'):'Bronnenoverzicht')+'</h1><span>'+(state.integrated?index.filter(x=>!x.record.demo).length.toLocaleString('nl-NL')+' bronkaarten + '+index.filter(x=>x.record.demo).length+' gemarkeerde ontwerpvoorbeelden':index.length.toLocaleString('nl-NL')+' bronkaarten · titels en metadata')+'</span></div><a href="./index.html#zoeken">Uitgebreide versie ↗</a></div>'+
 '<div class="compact-tabs" role="group" aria-label="Soort inhoud">'+Object.entries(tabs).map(([id,label])=>'<button data-content-type="'+id+'" aria-pressed="'+(type===id)+'">'+icon(id||'all')+label+' <small>'+refined.results.filter(h=>!id||contentTypeOf(h.record)===id).length+'</small></button>').join('')+'</div>'+
 '<form id="refine-search" class="compact-toolbar"><div class="compact-tools"><label>Aanvullende trefwoorden<input id="refine-extra" type="search" maxlength="200" autocomplete="off" spellcheck="false" value="'+esc(refinement.extra)+'" placeholder="Verfijn binnen deze resultaten"></label><button type="submit">'+icon('search')+'Verfijnen</button><label><span>'+icon('sort')+'Volgorde</span><select id="refine-sort">'+options({relevance:'Overeenkomst',used:'Meest gebruikt · sessie',source:'Bron, daarna alfabet',alphabet:'Alfabet A–Z'},refinement.sort,'Kies').replace('<option value="">Kies</option>','')+'</select></label></div>'+
 '<details id="compact-filters" '+(state.filtersOpen?'open':'')+'><summary>'+icon('filter')+'Filters'+(active?' · '+active+' actief':'')+'</summary><div class="refine-filters"><label>Soort informatie<select id="refine-kind">'+options(kinds,refinement.kind,'Alle soorten')+'</select></label><label>Doelgroep<select id="refine-audience">'+options({professional:'Zorgprofessionals',patient:'Patiënten en naasten',unknown:'Niet vastgelegd'},refinement.audience,'Alle doelgroepen')+'</select></label><label>Vakgebied<select id="refine-specialty">'+options({...specialties,unknown:'Niet ingedeeld'},refinement.specialty,'Alle vakgebieden')+'</select></label><label>Toegang<select id="refine-access">'+options({locked:'Mogelijk inloggen',unflagged:'Niet als afgeschermd gemarkeerd',unknown:'Niet vastgelegd'},refinement.access,'Alle statussen')+'</select></label></div><label class="toggle"><input id="search-complete" type="checkbox" '+(complete?'checked':'')+'>Alle hoofdzoektermen vereist</label><p>Kenmerken en aanvullende termen combineren met EN. Niet-ingedeelde bronnen vallen buiten specifieke vakgebieden.</p></details><div class="compact-toolbar-foot"><button type="button" id="refine-reset">'+icon('reset')+'Wis verfijning</button><details><summary>'+icon('info')+'Over dit overzicht</summary><p>Alleen brongegevens, geen volledige documentteksten. Overeenkomst is tekstoverlap; Details toont de vindplaatsen. Meest gebruikt telt geopende bronkaarten in deze sessie, zonder opslag of verzending.</p><p>'+(state.integrated?'De interfaces zijn samengevoegd. De 15 Inforium-kaarten zijn ontwerpvoorbeelden, geen gekoppelde patiëntartikelen of actuele nieuwsfeed.':'Patiënteninformatie en nieuws komen nu uit de bestaande catalogus. De koppeling met Inforium Advanced volgt later; er is nog geen Inforium-feed actief.')+'</p><a href="https://mediwebs.github.io/Inforium-advanced/" target="_blank" rel="noopener noreferrer">Bekijk Inforium Advanced ↗</a></details></div></form>'+
 '<div class="compact-result-count" role="status">'+rows.length+' resultaten'+(query?' voor “'+esc(query)+'”':'')+' · pagina '+(page+1)+'/'+pages+'</div>'+
 (!collections.size?'<div class="empty">Selecteer ten minste één broncollectie bovenaan.</div>':response.error||refined.error?'<div class="notice" role="alert">'+esc(response.error||refined.error)+'</div>':rows.length?'<div class="compact-grid">'+rows.slice(page*12,page*12+12).map(h=>card(h.record,false,h)).join('')+'</div><div class="actions compact-pages"><button id="search-prev" '+(!page?'disabled':'')+'>'+icon('left')+'Vorige</button><button id="search-next" '+(page+1>=pages?'disabled':'')+'>Volgende'+icon('right')+'</button></div>':'<div class="empty">Geen resultaten. Probeer andere trefwoorden of wis de verfijning.</div>');
 return {html,page,hits:rows};
}
