import {ANSWER_PASSAGES,composeSourceAnswer} from './answer-passages.js';
import {searchResources,normalize,SOURCE_COLLECTIONS} from './search.js';
import {patientLink} from './patient-sharing.js';
import {sourceUrl} from './compact.js';
import {icon} from './icons.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const filler=new Set('welke wat hoe waar wanneer waarom wie is zijn kan kun kunnen wil wilt ik je jij u we wij het de een en of van voor bij met in op over aan om te als informatie informatiemateriaal bronnen bron graag vinden zoek zoeken vraag geef geven vertellen weten advies moet doen mijn heeft heb hebben er deze dit dat ouders ouder'.split(' '));
export function chatAnswer(index,question,favorites,collections){
 const terms=[...new Set(normalize(question).split(' ').filter(t=>t&&!filler.has(t)))];
 if(!terms.length)return {question,error:'Noem een onderwerp, bijvoorbeeld slapen, voeding of taalontwikkeling.',hits:[],packages:[],patientIds:[]};
 if(terms.length>12)return {question,error:'Stel een kortere vraag met maximaal twaalf inhoudelijke trefwoorden.',hits:[],packages:[],patientIds:[]};
 const query=terms.join(' '),found=searchResources(index,query,{collections});
 const safe=found.results.filter(h=>!h.record.demo&&!h.record.link_review&&safeUrl(h.record)&&h.matches.some(m=>['Titel','Catalogustrefwoord','Alternatieve titel in export','Onderwerp','Klachttrefwoord in bronrecord'].includes(m.field)));
 const contentIds=new Set(ANSWER_PASSAGES.filter(p=>p.match.test(question.toLowerCase())).map(p=>p.id));
 const contentHits=index.filter(x=>contentIds.has(x.record.id)&&collections.includes(x.record.collection)&&!x.record.link_review&&safeUrl(x.record)).map(x=>safe.find(h=>h.record.id===x.record.id)||{record:x.record,score:0,matched:0,total:terms.length,matches:[],missing:terms});
 const hits=[...contentHits,...safe.filter(h=>!contentIds.has(h.record.id))].slice(0,6),byId=new Map(safe.map(h=>[h.record.id,h]));
 const packages=favorites.packages.map(p=>{const matched=p.cards.filter(id=>byId.has(id));return {...p,matched,score:matched.reduce((n,id)=>n+byId.get(id).score,0)};}).filter(p=>p.matched.length).sort((a,b)=>b.matched.length-a.matched.length||b.score-a.score).slice(0,3);
 return {question,query,terms,hits,packages,...composeSourceAnswer(hits,question),patientIds:hits.filter(h=>patientLink(h.record)).map(h=>h.record.id),favoriteIds:hits.filter(h=>favorites.cards.includes(h.record.id)).map(h=>h.record.id),collections:[...collections]};
}
function safeUrl(r){try{const u=new URL(sourceUrl(r));return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
function response(a,turn,selected=new Set(),answers=new Map()){
 if(a.error)return '<p>'+esc(a.error)+'</p>';
 if(!a.hits.length)return '<p>Ik vind geen passende bronkaart binnen de geselecteerde bronnen. Probeer een ander trefwoord of pas je bronselectie aan bij Zoeken. Ik kan hier geen inhoudelijk antwoord onderbouwen.</p>';
 const group=(title,patient)=>'<h3>'+title+'</h3><div class="chat-source-list">'+(a.hits.filter(h=>!!patientLink(h.record)===patient).map(h=>'<article class="chat-source-choice"><label><input type="checkbox" data-chat-source="'+esc(h.record.id)+'" '+(selected.has(h.record.id)?'checked':'')+'> <span>In consultmap</span></label><a href="'+esc(safeUrl(h.record))+'" target="_blank" rel="noopener noreferrer">'+'['+(a.hits.findIndex(x=>x.record.id===h.record.id)+1)+'] '+esc(h.record.title)+' ↗</a><small>'+esc(SOURCE_COLLECTIONS[h.record.collection]||h.record.owner)+'</small><details><summary>Waarom deze bron?</summary><p>'+(a.passages?.some(p=>p.id===h.record.id)?'Deze bron onderbouwt een tekstgedeelte van het antwoord.':'Gevonden op overeenkomst met je zoekwoorden; niet gebruikt voor de antwoordtekst.')+'</p><button data-open="'+esc(h.record.id)+'">Details en herkomst</button></details></article>').join('')||'<p>Geen passende bron gevonden in de huidige selectie.</p>')+'</div>';
 return '<section class="chat-text-answer"><h3>Antwoord in tekst</h3>'+(a.answer?'<p class="ia-caption">Algemene toelichting op het onderwerp. Controleer de bron voor de volledige context; geen beoordeling van een individuele situatie.</p>'+a.passages.map(p=>'<p>'+esc(p.text)+' <a href="'+esc(p.url)+'" target="_blank" rel="noopener noreferrer">['+(a.hits.findIndex(h=>h.record.id===p.id)+1)+']</a></p>').join('')+'<details><summary>Herkomst antwoord</summary>'+a.passages.map(p=>'<p>'+esc(p.section)+' · bron geraadpleegd '+esc(p.consultedAt)+' · niet klinisch beoordeeld</p>').join('')+'</details><label class="answer-select"><input type="checkbox" data-chat-answer="'+turn+'" '+(answers.has(a.answer)?'checked':'')+'> Antwoordtekst in consultmap</label>':'<p>Voor deze vraag is nog geen inhoudelijke bronpassage opgenomen. Daarom kan ik hier geen onderbouwd tekstantwoord geven. Je kunt de gevonden bronnen wel afzonderlijk bewaren.</p>')+'</section>'+group('Professionele bronnen',false)+group('Cliëntinformatie',true)+'<div class="consult-next"><a href="#board">Bekijk consultmap ('+(selected.size+answers.size)+') →</a><p>Kies hierboven wat je wilt bewaren. Sla je selectie in de consultmap op als werkpakket in Favorieten.</p></div>'+(a.packages.length?'<details><summary>Passende favoriete werkpakketten ('+a.packages.length+')</summary>'+a.packages.map(p=>'<p>'+esc(p.name)+' <button data-restore-package="'+esc(p.id)+'">In consultmap</button></p>').join('')+'</details>':'');
}
export function chatPanel(history,simple=false,selected=new Set(),answers=new Map()){if(simple)return simplePanel(history,selected,answers);return '<section class="jgz-chat" aria-labelledby="chat-title"><div class="chat-header"><div><p class="ia-eyebrow">JGZ · EXPERIMENTELE CHATVERSIE</p><h1 id="chat-title">Stel je vraag aan de bronassistent</h1><p>Vind bronnen, je favoriete werkpakketten en informatie om te delen.</p></div>'+icon('communication')+'</div><form id="jgz-chat-form"><label for="chat-question">Je vraag</label><div class="chat-input-row"><input id="chat-question" type="search" maxlength="400" required autocomplete="off" placeholder="Bijvoorbeeld: welke informatie is er over slaapproblemen?" aria-describedby="chat-help"><button class="primary" type="submit">'+icon('send')+'Stel vraag</button></div><small id="chat-help">Elke vraag wordt afzonderlijk gezocht. Alleen de laatste vijf vragen blijven tijdelijk in dit tabblad; ze worden alleen opgeslagen als je expliciet een werkpakket bewaart.</small></form><p class="chat-boundary">Zoekt lokaal in de aangevinkte broncollecties. Favorieten worden bij het eerste bezoek gekopieerd uit JGZ en daarna apart bewaard. Geen AI-model of volledige richtlijnteksten gekoppeld. Gebruik algemene vragen zonder patiëntgegevens.</p><div class="chat-history" role="log" aria-label="Vragen en bronnenantwoorden">'+(history.length?history.map((a,i)=>'<div class="chat-question"><strong>Jouw vraag</strong><p>'+esc(a.question)+'</p></div><div class="chat-answer"><strong>Bronassistent</strong>'+response(a,i,selected,answers)+'</div>').join(''):'<div class="chat-empty">Waar zoek je informatie over?<div class="actions"><button data-chat-example="Welke informatie is er over slaapproblemen?">Slapen</button><button data-chat-example="Welke bronnen zijn er over taalontwikkeling?">Taalontwikkeling</button><button data-chat-example="Welke informatie is er over borstvoeding?">Borstvoeding</button></div></div>')+'</div><div class="actions"><button id="chat-clear">Wis gesprek</button><a href="./jgz.html#start">Naar de bestaande JGZ-versie ↗</a></div><p id="chat-status" role="status"></p></section>';}

function simplePanel(history,selected,answers){return '<section class="jgz-chat simple-chat '+(history.length?'has-answer':'')+'" aria-labelledby="chat-title"><h1 id="chat-title">Waar zoek je informatie over?</h1><p class="simple-intro">Stel je vraag. Vind betrouwbare JGZ-bronnen.</p><form id="jgz-chat-form"><label for="chat-question">Je vraag</label><div class="chat-input-row"><input id="chat-question" type="search" maxlength="400" required autocomplete="off" placeholder="Bijvoorbeeld: slecht slapen" aria-describedby="chat-help"><button class="primary" type="submit">Zoek antwoord '+icon('search')+'</button></div><small id="chat-help">Gebruik een algemene vraag, zonder patiëntgegevens.</small></form>'+(history.length?'<div class="chat-history" role="log" aria-label="Vraag en bronnenantwoord">'+history.map((a,i)=>'<div class="chat-question"><strong>Je vroeg</strong><p>'+esc(a.question)+'</p></div><div class="chat-answer"><h2>Gevonden voor jouw vraag</h2>'+response(a,i,selected,answers)+'</div>').join('')+'</div><button id="chat-clear">Nieuwe vraag · wis antwoord</button>':'<div class="simple-examples"><span>Probeer eens</span><button data-chat-example="slaapproblemen">Slapen</button><button data-chat-example="taalontwikkeling">Taalontwikkeling</button><button data-chat-example="borstvoeding">Borstvoeding</button></div><p class="simple-note">Tekst en bronnen afzonderlijk bewaren. Geen patiëntgegevens.</p>')+'<p id="chat-status" role="status"></p></section>';}
