import {answerText} from './package-content.js';
import {searchResources,normalize,SOURCE_COLLECTIONS} from './search.js';
import {patientLink} from './patient-sharing.js';
import {sourceUrl} from './compact.js';
import {icon} from './icons.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const filler=new Set('welke wat hoe waar wanneer waarom wie is zijn kan kun kunnen wil wilt ik je jij u we wij het de een en of van voor bij met in op over aan om te als informatie informatiemateriaal bronnen bron graag vinden zoek zoeken vraag geef geven vertellen weten advies moet doen mijn heeft heb hebben er deze dit dat ouders ouder'.split(' '));
export function chatAnswer(index,question,favorites,collections){
 const terms=[...new Set(normalize(question).split(' ').filter(t=>t&&!filler.has(t)))];
 if(!terms.length)return {question,error:'Noem een onderwerp, bijvoorbeeld slapen, voeding of taalontwikkeling.',hits:[],packages:[],patientIds:[]};
 if(terms.length>12)return {question,error:'Stel een kortere vraag met maximaal twaalf inhoudelijke trefwoorden.',hits:[],packages:[],patientIds:[]};
 const query=terms.join(' '),found=searchResources(index,query,{collections});
 const safe=found.results.filter(h=>!h.record.demo&&!h.record.link_review&&safeUrl(h.record)&&h.matches.some(m=>['Titel','Catalogustrefwoord','Alternatieve titel in export','Onderwerp','Klachttrefwoord in bronrecord'].includes(m.field)));
 const hits=safe.slice(0,6),byId=new Map(safe.map(h=>[h.record.id,h]));
 const packages=favorites.packages.map(p=>{const matched=p.cards.filter(id=>byId.has(id));return {...p,matched,score:matched.reduce((n,id)=>n+byId.get(id).score,0)};}).filter(p=>p.matched.length).sort((a,b)=>b.matched.length-a.matched.length||b.score-a.score).slice(0,3);
 return {question,query,terms,hits,packages,answer:answerText(hits),patientIds:hits.filter(h=>patientLink(h.record)).map(h=>h.record.id),favoriteIds:hits.filter(h=>favorites.cards.includes(h.record.id)).map(h=>h.record.id),collections:[...collections]};
}
function safeUrl(r){try{const u=new URL(sourceUrl(r));return u.protocol==='https:'&&!u.username&&!u.password?u.href:null;}catch{return null;}}
function response(a,turn){
 if(a.error)return '<p>'+esc(a.error)+'</p>';
 if(!a.hits.length)return '<p>Ik vind geen passende bronkaart binnen de geselecteerde bronnen. Probeer een ander trefwoord of kies meer bronnen bovenaan. Ik kan hier geen inhoudelijk antwoord onderbouwen.</p>';
 const professional=a.hits.map((h,i)=>({h,i})).filter(x=>!patientLink(x.h.record)),patient=a.hits.map((h,i)=>({h,i})).filter(x=>patientLink(x.h.record));
 const refs=items=>items.map(({h,i})=>'<a href="'+esc(safeUrl(h.record))+'" target="_blank" rel="noopener noreferrer">'+esc(h.record.title)+' ['+(i+1)+']</a>').join('; ');
 return '<p>Voor <strong>'+esc(a.query)+'</strong> vind ik de volgende aanknopingspunten in de catalogus.</p>'+(professional.length?'<p><strong>Professionele informatie:</strong> '+refs(professional)+'.</p>':'<p>Onder de eerste resultaten vind ik geen professionele bron. Dit is geen bewijs dat er geen richtlijn bestaat.</p>')+(patient.length?'<p><strong>Om met ouders of jongeren te bespreken:</strong> '+refs(patient)+'.</p>':'')+'<p class="ia-caption">Dit is een bronnenantwoord op basis van titels en trefwoorden, geen inhoudelijke samenvatting of behandeladvies. Controleer de volledige tekst bij de bron.</p><details><summary>Gebruikte bronnen en waarom ze passen ('+a.hits.length+')</summary><ol class="chat-citations">'+a.hits.map(h=>'<li><a href="'+esc(safeUrl(h.record))+'" target="_blank" rel="noopener noreferrer">'+esc(h.record.title)+'</a><small>'+esc(SOURCE_COLLECTIONS[h.record.collection]||h.record.owner)+(a.favoriteIds.includes(h.record.id)?' · ★ Favoriet':'')+'</small><p>'+h.matched+'/'+h.total+' trefwoorden: '+h.matches.map(m=>esc(m.term)+' ('+esc(m.field)+')').join(', ')+(h.missing.length?'. Niet gevonden: '+h.missing.map(esc).join(', '):'')+'</p><button data-open="'+esc(h.record.id)+'">Details en herkomst</button></li>').join('')+'</ol></details><button data-chat-save="'+turn+'">Antwoord en bronnen opslaan als werkpakket</button><div class="chat-suggestions"><h3>Passend bij je consultmap</h3>'+(a.packages.length?a.packages.map(p=>'<article><strong>'+esc(p.name||'Werkpakket')+'</strong><p>'+p.matched.length+' bron(nen) in dit favoriete werkpakket passen op de zoektermen.</p><div class="actions"><button data-chat-package="'+esc(p.id)+'">Bekijk patiëntenpakket</button><button data-restore-package="'+esc(p.id)+'">Toevoegen aan consultmap</button></div></article>').join(''):'<p>Geen passend favoriet werkpakket gevonden. Sla een werkpakket op in Mijn Favorieten om het bij een volgende vraag terug te vinden.</p>')+(a.patientIds.length?'<article><strong>Voorstel informatiepakket</strong><p>'+a.patientIds.length+' patiëntenbron(nen) uit dit antwoord. Selectie op tekstovereenkomst; nog door jou te beoordelen.</p><div class="actions"><button data-chat-preview="'+turn+'">Bekijk informatiepakket</button><button data-chat-add="'+turn+'">Patiëntenlinks in consultmap</button></div></article>':'')+'</div>';
}
export function chatPanel(history){return '<section class="jgz-chat" aria-labelledby="chat-title"><div class="chat-header"><div><p class="ia-eyebrow">JGZ · EXPERIMENTELE CHATVERSIE</p><h1 id="chat-title">Stel je vraag aan de bronassistent</h1><p>Vind bronnen, je favoriete werkpakketten en informatie om te delen.</p></div>'+icon('communication')+'</div><form id="jgz-chat-form"><label for="chat-question">Je vraag</label><div class="chat-input-row"><input id="chat-question" type="search" maxlength="400" required autocomplete="off" placeholder="Bijvoorbeeld: welke informatie is er over slaapproblemen?" aria-describedby="chat-help"><button class="primary" type="submit">'+icon('send')+'Stel vraag</button></div><small id="chat-help">Elke vraag wordt afzonderlijk gezocht. Alleen de laatste vijf vragen blijven tijdelijk in dit tabblad; ze worden alleen opgeslagen als je expliciet een werkpakket bewaart.</small></form><p class="chat-boundary">Zoekt lokaal in de aangevinkte broncollecties. Favorieten worden bij het eerste bezoek gekopieerd uit JGZ en daarna apart bewaard. Geen AI-model of volledige richtlijnteksten gekoppeld. Gebruik algemene vragen zonder patiëntgegevens.</p><div class="chat-history" role="log" aria-label="Vragen en bronnenantwoorden">'+(history.length?history.map((a,i)=>'<div class="chat-question"><strong>Jouw vraag</strong><p>'+esc(a.question)+'</p></div><div class="chat-answer"><strong>Bronassistent</strong>'+response(a,i)+'</div>').join(''):'<div class="chat-empty">Waar zoek je informatie over?<div class="actions"><button data-chat-example="Welke informatie is er over slaapproblemen?">Slapen</button><button data-chat-example="Welke bronnen zijn er over taalontwikkeling?">Taalontwikkeling</button><button data-chat-example="Welke informatie is er over borstvoeding?">Borstvoeding</button></div></div>')+'</div><div class="actions"><button id="chat-clear">Wis gesprek</button><a href="./jgz.html#start">Naar de bestaande JGZ-versie ↗</a></div><p id="chat-status" role="status"></p></section>';}
